openapi: 3.0.0

info:
  title: Invotra Analytics API Proof of Concept
  version: v0.3
security:
  - APIKeyHeader: []
  - APISessionHeader: []
paths:
  /pageviews:
    get:
      tags:
        - Summary site statistics
      parameters:
        - $ref: '#/components/parameters/startDateParam'
        - $ref: '#/components/parameters/endDateParam'
        - $ref: '#/components/parameters/urlPatternParam'
        - $ref: '#/components/parameters/siteSectionParam'
      responses:
        '200':
          description: Returns summary page view site statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pageviews'
      description: Returns the site page views summary statstics.
  /downloads:
    get:
      tags:
        - Summary site statistics
      parameters:
        - $ref: '#/components/parameters/startDateParam'
        - $ref: '#/components/parameters/endDateParam'
        - $ref: '#/components/parameters/urlPatternParam'
        - $ref: '#/components/parameters/siteSectionParam'
      responses:
        '200':
          description: Returns summary dowload site statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/downloads'
      description: Returns the site downloads summary statstics.
  /outlinks:
    get:
      tags:
        - Summary site statistics
      parameters:
        - $ref: '#/components/parameters/startDateParam'
        - $ref: '#/components/parameters/endDateParam'
        - $ref: '#/components/parameters/urlPatternParam'
        - $ref: '#/components/parameters/siteSectionParam'
      responses:
        '200':
          description: Returns summary outlinks site statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/outlinks'
      description: Returns the site outlinks summary statstics.
  /list/pageviews:
    get:
      tags:
        - Itemised statistics
      parameters:
        - $ref: '#/components/parameters/startDateParam'
        - $ref: '#/components/parameters/endDateParam'
        - $ref: '#/components/parameters/urlPatternParam'
        - $ref: '#/components/parameters/siteSectionParam'
        - $ref: '#/components/parameters/pageParam'
      responses:
        '200':
          description: Returns summary page view site statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pageviews_list'
      description: Returns the site page views summary statstics.

  /list/downloads:
    get:
      tags:
        - Itemised statistics
      parameters:
        - $ref: '#/components/parameters/startDateParam'
        - $ref: '#/components/parameters/endDateParam'
        - $ref: '#/components/parameters/urlPatternParam'
        - $ref: '#/components/parameters/siteSectionParam'
        - $ref: '#/components/parameters/pageParam'
      responses:
        '200':
          description: Returns summary outlinks site statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/downloads_list'
      description: Returns the site outlinks summary statstics.
  /list/outlinks:
    get:
      tags:
        - Itemised statistics
      parameters:
        - $ref: '#/components/parameters/startDateParam'
        - $ref: '#/components/parameters/endDateParam'
        - $ref: '#/components/parameters/urlPatternParam'
        - $ref: '#/components/parameters/siteSectionParam'
        - $ref: '#/components/parameters/pageParam'
      responses:
        '200':
          description: Returns summary outlinks site statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/outlinks_list'
      description: Returns the site outlinks summary statstics.
  /list/titles:
    get:
      tags:
        - Itemised statistics
      parameters:
        - $ref: '#/components/parameters/startDateParam'
        - $ref: '#/components/parameters/endDateParam'
        - $ref: '#/components/parameters/urlPatternParam'
        - $ref: '#/components/parameters/siteSectionParam'
        - $ref: '#/components/parameters/pageParam'
      responses:
        '200':
          description: Returns summary outlinks site statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/titles_list'
      description: Returns the site outlinks summary statstics.
components:
  parameters:
    startDateParam:
      in: query
      name: startDate
      schema:
        type: string
        example: '2019-01-01'
      description: start date filter
      required: false
    endDateParam:
      in: query
      name: endDate
      schema:
        type: string
        example: '2019-01-23'
      description: end date filter
      required: false
    urlPatternParam:
      in: query
      name: urlPattern
      schema:
        type: string
        example: '*organisation*'
      description: URL pattern, that accepts wildcards
      required: false
    siteSectionParam:
      in: query
      name: siteSection
      schema:
        type: string
        example: '12345-2222-*'
      description: site-section pattern, that accepts wildcards
      required: false
    pageParam:
      in: query
      name: page
      schema:
        type: integer
        example: '221'
      description: page number, starting with 0
      required: false
  schemas:
    pageviews:
      properties:
        total_page_views:
          description: The total pages views by visitor id. After more testing, will probably be deprecated.
          type: integer
          example: 48
        total_user_page_views:
          description: The total pages views, that had a uid
          type: integer
          example: 29
        unique_page_views:
          description: Unique page views, counted by visitor. After more testing, will probably be deprecated.
          type: integer
          example: 30
        user_page_views:
          description: Unique page views, counted by visitor
          type: integer
          example: 30
    pageviews_list:
      properties:
        count:
          type: integer
          description: total count of results
          example: 115207
        pages:
          type: integer
          description: total count of pages
          example: 577
        data:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
                description: url of page
                example: 42.invotra.com/invotra/my-workplace/my-feed
              pageviews:
                type: integer
                description: total views of url
                example: 150145
              unique_pageviews:
                type: integer
                description: unique views of url
                example: 612
    downloads:
      properties:
        visitor_total_downloads:
          description: The total downloads
          type: integer
          example: 48
        visitor_unique_downloads:
          description: The unique dowloads
          type: integer
          example: 29
        user_total_downloads:
          description: Total downloads, with uid
          type: integer
          example: 30
        user_unique_downloads:
          description: Unique downloads, with uid
          type: integer
          example: 30
    downloads_list:
      properties:
        count:
          type: integer
          description: total count of results
          example: 115207
        pages:
          type: integer
          description: total count of pages
          example: 577
        data:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
                description: url of download
                example: 'https://42.invotra.com/sites/default/files/Office floorplan - Chertsey house 2017.png'
              download:
                type: integer
                description: total downloads of url
                example: 150145
              unique_download:
                type: integer
                description: unique downloads of url
                example: 612
    outlinks:
      properties:
        visitor_total_outlinks:
          description: The total outlinks
          type: integer
          example: 48
        visitor_unique_outlinks:
          description: The unique outlinks
          type: integer
          example: 29
        user_total_outlinks:
          description: Total outlinks, with uid
          type: integer
          example: 30
        user_unique_outlinks:
          description: Unique outlinks, with uid
          type: integer
          example: 30
    outlinks_list:
      properties:
        count:
          type: integer
          description: total count of results
          example: 115207
        pages:
          type: integer
          description: total count of pages
          example: 577
        data:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
                description: url of outlink
                example: google.com
              outlinks:
                type: integer
                description: total follows of url
                example: 150145
              unique_outlinks:
                type: integer
                description: unique follows of url
                example: 612
    titles_list:
      properties:
        count:
          type: integer
          description: total count of results
          example: 115207
        pages:
          type: integer
          description: total count of pages
          example: 577
        data:
          type: array
          items:
            type: object
            properties:
              # this may not be possible as there is no unique mapping from title to url
              # it is a many-to-many relationship. We may have to drop it.
              url:
                type: string
                description: url of title
                example: google.com
              titles:
                type: integer
                description: total follows of title
                example: 150145
              unique_titles:
                type: integer
                description: unique follows of title
                example: 612

