swagger: '2.0'
info:
  title: InvotraPrivateAPI
  version: v0.1
host: dev.invotra.com
consumes:
  - application/json
produces:
  - application/json
basePath: /api/v0.1
schemes:
  - http
security:
  - APIKeyHeader: []
tags:
  - name: sessions
    description: Session management
  - name: notifications
    description: Notification messages
  - name: feeds
    description: Feed update status
  - name: pdf export
    description: PDF export
paths:
  '/sessions/{session_hash}':
    parameters:
      - name: session_hash
        description: The session ID.
        in: path
        type: string
        pattern: '^[a-f0-9]{64}$'
        required: true
    put:
      tags:
        - sessions
      summary: Create or update a user session.
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/session-schema'
          required: true
      responses:
        '200':
          description: An existing session was updated.
        '201':
          description: A new session was created.
        '400':
          description: The JSON was malformed.
        '422':
          description: JSON schema validation failed.
    delete:
      tags:
        - sessions
      summary: Destroy a user session.
      responses:
        '200':
          description: The session was destroyed.
        '400':
          description: The JSON was malformed.
        '404':
          description: The session did not exist.
        '422':
          description: JSON schema validation failed.
  '/sessions/users/{user_id}':
    parameters:
      - name: user_id
        in: path
        type: string
        description: The Invotra UUID of the user.
        pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        required: true
    delete:
      tags:
        - sessions
      summary: Destroy all sessions of a user.
      responses:
        '200':
          description: 'All the user''s sessions were destroyed, or the user had no sessions.'
        '400':
          description: The user UUID was malformed.
        '404':
          description: The user did not exist.
  '/notifications/{user_id}':
    parameters:
      - name: user_id
        in: path
        type: string
        description: The Invotra UUID of the notification recipient user.
        pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        required: true
    get:
      tags:
        - notifications
      summary: Get all notifications for a user.
      responses:
        '200':
          description: 'A list of the user''s notifications, or an empty array if there are none.'
          schema:
            $ref: '#/definitions/notification-list-schema'
        '400':
          description: The UUID was malformed.
        '404':
          description: The user was not found.
    post:
      tags:
        - notifications
      summary: Add a notification.
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/notification-schema'
          required: true
      responses:
        '201':
          description: The notification was added.
          headers:
            Location:
              type: string
              description: |
                The URL of the newly added notification (.../notifications/{user_id}/{notification_id}).
        '400':
          description: The UUID or JSON was malformed.
        '404':
          description: The user was not found.
        '422':
          description: JSON schema validation failed.
    delete:
      tags:
        - notifications
      summary: Delete all notifications for a user.
      responses:
        '200':
          description: 'The notifications were deleted, or the user had no notifications.'
        '400':
          description: The UUID was malformed.
        '404':
          description: The user was not found.
  '/notifications/{user_id}/{notification_id}':
    delete:
      tags:
        - notifications
      summary: Delete a notification.
      parameters:
        - name: user_id
          in: path
          type: string
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
          description: The Invotra UUID of the user.
          required: true
        - name: notification_id
          in: path
          type: string
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
          description: The UUID of the notification message.
          required: true
      responses:
        '200':
          description: The notification was deleted.
        '400':
          description: One or both of the UUIDs was malformed.
        '404':
          description: The user or the notification was not found.
  '/feeds/{user_id}':
    parameters:
      - name: user_id
        in: path
        type: string
        description: The Invotra UUID of the feed owner.
        pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        required: true
    get:
      tags:
        - feeds
      summary: Get the feed update status for a user.
      responses:
        '200':
          description: The feed update status.
          schema:
            $ref: '#/definitions/feed-schema'
        '404':
          description: The user was not found.
    put:
      tags:
        - feeds
      summary: Set the feed update status for a user.
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/feed-schema'
          required: true
      responses:
        '200':
          description: The feed update status was updated.
        '400':
          description: The JSON was malformed.
        '422':
          description: JSON schema validation failed.
  '/pdf-export/create-job/{content_uuid}':
    post:
      tags:
        - pdf export
      summary: Create a PDF export job.
      parameters:
        - name: uuid
          in: path
          type: string
          description: The UUID of the node to export.
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
          required: true
        - name: latest
          in: query
          type: boolean
          description: Whether to use the latest revision of each page.
          required: false
          default: false
      responses:
        '200':
          description: An existing PDF export job was found and returned to the client.
          schema:
            $ref: '#/definitions/pdf-export-job-schema'
        '201':
          description: A new PDF export job was created.
          schema:
            $ref: '#/definitions/pdf-export-job-schema'
        '400':
          description: A malformed UUID was supplied.
        '403':
          description: The user is not authorized to access this node.
        '404':
          description: The supplied UUID does not correspond to an existing node.
definitions:
  session-schema:
    properties:
      user_id:
        description: The Invotra UUID of the user
        type: string
        pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        example: 2df46a6e-6f73-4b09-b340-7cea68b6e5f6
      user_internal_id:
        description: The Drupal user ID
        type: integer
        example: 12345
      expiry:
        description: The number of seconds after which the session should expire
        type: integer
        example: 1209600
    required:
      - user_id
      - expiry
  notification-schema:
    properties:
      type:
        type: string
        description: The type of notification.
        example: invotra.user.mention
      message:
        type: string
        description: 'The notification message text, which may contain HTML.'
        example: Dorothy Whitehead mentioned you in a post
      link:
        type: string
        description: The URL that the notification should link to.
        example: 'https://www.example.com/post/interesting'
      image:
        type: string
        description: The URL of an image associated with the notification.
        example: 'https://www.example.com/sites/default/files/picture.jpg'
      timestamp:
        type: integer
        description: The timestamp of the notification (in seconds).
        example: 1442089320
      target_type:
        type: string
        description: The type of the notification target entity.
        example: node
      target_subtype:
        type: string
        description: The subtype (or "bundle") of the notification target entity.
        example: group_status
    required:
      - type
      - message
      - link
      - image
      - timestamp
      - target_type
      - target_subtype
  notification-schema-retrieve:
    allOf:
      - $ref: '#/definitions/notification-schema'
      - type: object
        properties:
          user_id:
            description: The UUID of the user.
            type: string
            pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
            example: 2df46a6e-6f73-4b09-b340-7cea68b6e5f6
          notification_id:
            description: The UUID of the notification message.
            type: string
            pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
            example: 52000da2-8513-4472-8395-4a080f662b48
        required:
          - user_id
          - notification_id
  notification-list-schema:
    type: array
    items:
      $ref: '#/definitions/notification-schema-retrieve'
  feed-schema:
    type: object
    properties:
      read:
        description: Boolean indicating whether the user has read the feed since the most recent item was added.
        type: boolean
        example: false
      item_id:
        description: The UUID of the most recent item in the feed.
        type: string
        pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        example: 2df46a6e-6f73-4b09-b340-7cea68b6e5f6
      timestamp:
        description: The Unix timestamp (in seconds) of when the most recent item was added to the feed.
        type: integer
        example: 1442089320
    required:
      - read
  pdf-export-job-schema:
    type: object
    properties:
      uuid:
        description: The UUID of the PDF export job.
        type: string
        pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        example: 2df46a6e-6f73-4b09-b340-7cea68b6e5f6
    required:
      - uuid
securityDefinitions:
  APIKeyHeader:
    type: apiKey
    in: header
    name: X-API-Key
