swagger: '2.0'
info:
  title: InvotraAPI
  version: v0.2
host: dev.invotra.com
basePath: /api/v0.2
schemes:
  - https
security:
  - APIKeyHeader: []
paths:
  /teams:
    get:
      parameters:
        - description: Filter by external ID.
          in: query
          name: external_id
          required: true
          type: string
      responses:
        '200':
          description: List of teams matching the filter criteria.
          schema:
            $ref: '#/definitions/uuid-list-schema'
        '404':
          description: No matching teams were found.
      description: Search for teams.
    post:
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/team-schema'
      responses:
        '201':
          description: The team was created successfully.
        '400':
          description: The team was not saved due to malformed JSON.
        '422':
          description: |
            The team was not saved due to Drupal validation failure or JSON
            schema validation failure.
      description: Provision a new team.
  '/teams/{team_id}':
    get:
      parameters:
        - description: The Invotra UUID of the team.
          in: path
          name: team_id
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
          required: true
          type: string
      responses:
        '200':
          description: Returns a single complete Team object.
          schema:
            $ref: '#/definitions/team-schema'
        '400':
          description: The supplied UUID was malformed.
        '404':
          description: The UUID does not correspond to an existing team.
      description: Get information about the team.
    put:
      parameters:
        - description: The Invotra UUID of the team.
          in: path
          name: team_id
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/team-schema-create'
      responses:
        '200':
          description: The team information was updated successfully.
        '400':
          description: The supplied UUID or JSON was malformed.
        '404':
          description: The UUID does not correspond to an existing team.
        '422':
          description: |
            The team was not updated due to a Drupal validation failure or a
            JSON schema validation failure.
      description: Update team information.
  '/teams/{team_id}/memberships':
    get:
      parameters:
        - description: The Invotra UUID of the team.
          in: path
          name: team_id
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
          required: true
          type: string
      responses:
        '200':
          description: |
            List of team members. If there are no members, an empty array.
          schema:
            $ref: '#/definitions/team-membership-list-schema'
        '400':
          description: The supplied UUID was malformed.
        '404':
          description: The UUID does not correspond to an existing team.
      description: Get a list of team members.
  '/teams/{team_id}/memberships/{user_id}':
    delete:
      parameters:
        - description: The Invotra UUID of the team.
          in: path
          name: team_id
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
          required: true
          type: string
        - description: The Invotra UUID of the user.
          in: path
          name: user_id
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
          required: true
          type: string
      responses:
        '200':
          description: The user has been removed from the team.
        '400':
          description: The UUID was malformed.
        '404':
          description: |
            The user or team does not exist, or the user was not a member
            of the team.
      description: Remove the user's membership of the team.
    put:
      parameters:
        - description: The Invotra UUID of the team.
          in: path
          name: team_id
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
          required: true
          type: string
        - description: The Invotra UUID of the user.
          in: path
          name: user_id
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
          required: true
          type: string
        - default: member
          enum:
            - admin
            - member
          in: query
          name: role_type
          required: true
          type: string
      responses:
        '200':
          description: The user's membership of this team was updated.
        '201':
          description: The user was added as a member of the team.
        '400':
          description: The UUID was malformed or the role type was invalid.
        '404':
          description: The user or team does not exist.
      description: Update information about a user's team membership.
  /users:
    get:
      parameters:
        - description: Filter by external ID.
          in: query
          name: external_id
          required: true
          type: string
      responses:
        '200':
          description: |
            List of users matching the filter criteria, or an empty array if no
            matching users are found.
          schema:
            $ref: '#/definitions/uuid-list-schema'
      description: Search for users.
    post:
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/user-schema-create'
      responses:
        '201':
          description: The user was created successfully.
        '400':
          description: The user was not saved due to malformed JSON.
        '409':
          description: |
            The user was not saved because the username or email address is
            already in use.
        '422':
          description: |
            The user was not saved due to Drupal validation failure (other than
            a duplicate username or email address) or JSON schema validation
            failure.
      description: Provision a new user in Invotra.
  '/users/{user_id}':
    get:
      parameters:
        - description: The Invotra UUID of the user.
          in: path
          name: user_id
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
          required: true
          type: string
      responses:
        '200':
          description: Returns a single complete user object.
          schema:
            $ref: '#/definitions/user-schema'
        '400':
          description: The supplied UUID was malformed.
        '404':
          description: No user with that UUID was found.
      description: Get the user's information.
    put:
      parameters:
        - description: The Invotra UUID of the user.
          in: path
          name: user_id
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/user-schema-update'
      responses:
        '200':
          description: The user's information was updated.
        '400':
          description: The supplied UUID or JSON was malformed.
        '404':
          description: The UUID does not correspond to an existing user.
        '409':
          description: |
            The user was not saved because the requested new username or email
            address is already in use by a different user.
        '422':
          description: |
            The user was not updated due to Drupal validation failure (other
            than a duplicate username or email address) or JSON schema
            validation failure.
      description: Update the user's information.
  /job_roles:
    get:
      parameters:
        - description: Filter by external ID.
          in: query
          name: external_id
          required: true
          type: string
      responses:
        '200':
          description: List of job roles matching the filter criteria.
          schema:
            $ref: '#/definitions/uuid-list-schema'
        '404':
          description: No matching job roles were found.
      description: Search for job roles.
    post:
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/job-role-schema'
      responses:
        '201':
          description: The job role was created successfully.
        '400':
          description: The job role was not saved due to malformed JSON.
        '422':
          description: |
            The job role was not saved due to Drupal validation failure or JSON
            schema validation failure.
      description: Provision a new job role.
  '/job_roles/{job_role_id}':
    get:
      parameters:
        - description: The Invotra UUID of the job role.
          in: path
          name: job_role_id
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
          required: true
          type: string
      responses:
        '200':
          description: Returns a single complete job role object.
          schema:
            $ref: '#/definitions/job-role-schema'
        '400':
          description: The supplied UUID was malformed.
        '404':
          description: The UUID does not correspond to an existing job role.
      description: Get information about the job role.
    put:
      parameters:
        - description: The Invotra UUID of the job role.
          in: path
          name: job_role_id
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/job-role-schema-create'
      responses:
        '200':
          description: The job role information was updated successfully.
        '400':
          description: The supplied UUID or JSON was malformed.
        '404':
          description: The UUID does not correspond to an existing job role.
        '422':
          description: |
            The job role was not updated due to a Drupal validation failure or a
            JSON schema validation failure.
      description: Update job role information.
definitions:
  team-membership-list-schema:
    properties:
      administrators:
        items:
          description: Invotra UUID of team administrators.
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
          type: string
        type: array
        uniqueItems: true
      description:
        description: 'This is a description of the team, optional.'
        type: string
      members:
        items:
          description: Invotra UUID of team members.
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
          type: string
        type: array
        uniqueItems: true
      parent_uuid:
        description: 'This is the Invotra UUID of the parent team, optional.'
        pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        type: string
      title:
        description: This is the name of the team
        type: string
      uuid:
        description: This is the Invotra UUID of the team.
        pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        type: string
    required:
      - uuid
      - title
    type: object
  team-schema:
    properties:
      description:
        description: 'This is a description of the team, optional.'
        type: string
      external_id:
        description: This is used to store the team's external reference id
        type: string
      parent_uuid:
        description: 'This is the Invotra UUID of the parent team, optional.'
        pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        type: string
      title:
        description: This is the name of the team
        type: string
      uuid:
        description: This is the Invotra UUID of the team.
        pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        type: string
    required:
      - uuid
      - title
    type: object
  team-schema-create:
    properties:
      description:
        description: 'This is a description of the team, optional.'
        type: string
      parent_uuid:
        description: 'This is the Invotra UUID of the parent team, optional.'
        pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        type: string
      title:
        description: This is the name of the team
        type: string
    required:
      - title
    type: object
  user-schema:
    properties:
      email:
        description: Users email address
        format: email
        type: string
      roles:
        items:
          default: Organisational user
          description: This is the default Invotra user role
          enum:
            - Organisational user
          type: string
        type: array
        uniqueItems: true
      status:
        default: Active
        description: Flag to indicate whether account is active or blocked
        enum:
          - Active
          - Blocked
        type: string
      username:
        description: The user's username
        type: string
      external_id:
        description: The user's external reference ID
        type: string
      home_phone:
        description: The user's home telephone number.
        type: string
      manager_uuid:
        description: This is the Invotra UUID of the user's manager.
        pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        type: string
      teams:
        items:
          properties:
            uuid:
              description: This is the Invotra UUID for the team.
              pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
              type: string
          type: object
        type: array
      display_name:
        default: Damian Robinson
        description: Display name for the user
        type: string
      firstname:
        description: The user's first name
        type: string
      surname:
        description: The user's surname
        type: string
      title:
        default: ''
        description: The user's title
        enum:
          - ''
          - Dr
          - Mr
          - Miss
          - Mrs
          - Ms
        type: string
      uuid:
        description: Invotra UUID assigned on creation of the user. Must be included when any updates are made to the user.
        pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        type: string
    type: object
  user-schema-create:
    allOf:
      - $ref: '#definitions/user-schema'
    required:
      - email
      - username
    type: object
  user-schema-update:
    allOf:
      - $ref: '#definitions/user-schema'
    required:
      - uuid
    type: object
  job-role-schema:
    properties:
      description:
        description: 'This is a description of the job role, optional.'
        type: string
      external_id:
        description: This is used to store the job role's external reference id
        type: string
      parent_uuid:
        description: 'This is the Invotra UUID of the parent job role, optional.'
        pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        type: string
      title:
        description: This is the name of the job role
        type: string
      uuid:
        description: This is the Invotra UUID of the job role.
        pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        type: string
    required:
      - uuid
      - title
    type: object
  job-role-schema-create:
    properties:
      description:
        description: 'This is a description of the job role, optional.'
        type: string
      parent_uuid:
        description: 'This is the Invotra UUID of the parent job role, optional.'
        pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        type: string
      title:
        description: This is the name of the job role
        type: string
    required:
      - title
    type: object
  uuid-list-schema:
    items:
      default: 00000000-0000-0000-0000-000000000000
      description: An array of UUIDs.
      pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
      type: string
    type: array
securityDefinitions:
  APIKeyHeader:
    type: apiKey
    in: header
    name: X-API-Key
