// tslint:disable
/**
 * Invotra API
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BlogSchemaAllOf1GeneralTopic
 */
export interface BlogSchemaAllOf1GeneralTopic {
    /**
     * Invotra UUID of the general topic.
     * @type {string}
     * @memberof BlogSchemaAllOf1GeneralTopic
     */
    uuid?: string;
    /**
     * This is the name of the general topic.
     * @type {string}
     * @memberof BlogSchemaAllOf1GeneralTopic
     */
    name?: string;
}


