// tslint:disable
/**
 * Invotra API
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BlogSchemaCommon } from './blog-schema-common';
import { BlogSchemaUpdateAllOf } from './blog-schema-update-all-of';
import { BlogSchemaUpdateAllOfGeneralTopic } from './blog-schema-update-all-of-general-topic';
import { BlogSchemaUpdateAllOfImage } from './blog-schema-update-all-of-image';

/**
 * @type BlogSchemaUpdate
 * @export
 */
export type BlogSchemaUpdate = BlogSchemaCommon & BlogSchemaUpdateAllOf;



