// tslint:disable
/**
 * InvotraAPI
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CustomContentSchemaAllOf } from './custom-content-schema-all-of';
import { CustomContentSchemaAllOf1 } from './custom-content-schema-all-of1';
import { CustomContentSchemaAllOf1Grades } from './custom-content-schema-all-of1-grades';
import { CustomContentSchemaAllOf1Locations } from './custom-content-schema-all-of1-locations';
import { CustomContentSchemaAllOf1Regions } from './custom-content-schema-all-of1-regions';
import { CustomContentSchemaAllOf1SiteSection } from './custom-content-schema-all-of1-site-section';
import { CustomContentSchemaAllOf1Team } from './custom-content-schema-all-of1-team';
import { CustomContentSchemaCommon } from './custom-content-schema-common';
import { CustomContentSchemaCommonRelatedContentLinks } from './custom-content-schema-common-related-content-links';
import { CustomContentSchemaCommonRelatedExternalLinks } from './custom-content-schema-common-related-external-links';
import { FileSchema } from './file-schema';
import { UserTrimmedSchema } from './user-trimmed-schema';

/**
 * @type CustomContentSchema
 * @export
 */
export type CustomContentSchema = CustomContentSchemaAllOf & CustomContentSchemaAllOf1 & CustomContentSchemaCommon;



