// tslint:disable
/**
 * InvotraAPI
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GeneralTopicSchemaCommon
 */
export interface GeneralTopicSchemaCommon {
    /**
     * Name of the general topic.
     * @type {string}
     * @memberof GeneralTopicSchemaCommon
     */
    name?: string;
    /**
     * Description of the general topic.
     * @type {string}
     * @memberof GeneralTopicSchemaCommon
     */
    description?: string;
    /**
     * The general topic external reference id.
     * @type {string}
     * @memberof GeneralTopicSchemaCommon
     */
    external_id?: string;
    /**
     * Invotra UUID of the parent general topic.
     * @type {string}
     * @memberof GeneralTopicSchemaCommon
     */
    parent_uuid?: string;
    /**
     * Indicates that this general topic is published.
     * @type {boolean}
     * @memberof GeneralTopicSchemaCommon
     */
    published?: boolean;
    /**
     * Determines the position of a general topic in the hierarchy in relation to its siblings.
     * @type {number}
     * @memberof GeneralTopicSchemaCommon
     */
    weight?: number;
}


