// tslint:disable
/**
 * InvotraAPI
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GroupPollSchemaCreateAllOfAuthor } from './group-poll-schema-create-all-of-author';
import { GroupPollSchemaCreateAllOfGroup } from './group-poll-schema-create-all-of-group';
import { GroupPollSchemaCreateAllOfOptions } from './group-poll-schema-create-all-of-options';

/**
 * 
 * @export
 * @interface GroupPollSchemaCreateAllOf
 */
export interface GroupPollSchemaCreateAllOf {
    /**
     * 
     * @type {GroupPollSchemaCreateAllOfAuthor}
     * @memberof GroupPollSchemaCreateAllOf
     */
    author?: GroupPollSchemaCreateAllOfAuthor;
    /**
     * 
     * @type {GroupPollSchemaCreateAllOfGroup}
     * @memberof GroupPollSchemaCreateAllOf
     */
    group: GroupPollSchemaCreateAllOfGroup;
    /**
     * The options for this group poll.
     * @type {Array<GroupPollSchemaCreateAllOfOptions>}
     * @memberof GroupPollSchemaCreateAllOf
     */
    options: Array<GroupPollSchemaCreateAllOfOptions>;
}


