// tslint:disable
/**
 * Invotra API
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ListListContentSchema } from './list-list-content-schema';
import { ListListLinkSchema } from './list-list-link-schema';
import { ListListSiteSectionSchema } from './list-list-site-section-schema';

/**
 * 
 * @export
 * @interface ListSchemaCommon
 */
export interface ListSchemaCommon {
    /**
     * Title of the list.
     * @type {string}
     * @memberof ListSchemaCommon
     */
    title?: string;
    /**
     * The body of the list.
     * @type {string}
     * @memberof ListSchemaCommon
     */
    body?: string;
    /**
     * Indicates the workflow state of the list.
     * @type {string}
     * @memberof ListSchemaCommon
     */
    state?: ListSchemaCommonStateEnum;
    /**
     * The review date timestamp for the list (in seconds).
     * @type {number}
     * @memberof ListSchemaCommon
     */
    review_date_timestamp?: number;
    /**
     * List of content and links in the list.
     * @type {Array<ListListContentSchema | ListListSiteSectionSchema | ListListLinkSchema>}
     * @memberof ListSchemaCommon
     */
    list?: Array<ListListContentSchema | ListListSiteSectionSchema | ListListLinkSchema>;
}

/**
    * @export
    * @enum {string}
    */
export enum ListSchemaCommonStateEnum {
    Draft = 'draft',
    NeedsReview = 'needs_review',
    Reviewed = 'reviewed',
    Published = 'published',
    Unpublished = 'unpublished'
}



