// tslint:disable
/**
 * InvotraAPI
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LocationSiteSchemaCommonAllOf
 */
export interface LocationSiteSchemaCommonAllOf {
    /**
     * The first line of the location\'s postal address.
     * @type {string}
     * @memberof LocationSiteSchemaCommonAllOf
     */
    address1?: string;
    /**
     * The second line of the location\'s postal address.
     * @type {string}
     * @memberof LocationSiteSchemaCommonAllOf
     */
    address2?: string;
    /**
     * The third line of the location\'s postal address.
     * @type {string}
     * @memberof LocationSiteSchemaCommonAllOf
     */
    address3?: string;
    /**
     * The town where the location is.
     * @type {string}
     * @memberof LocationSiteSchemaCommonAllOf
     */
    town?: string;
    /**
     * The location\'s postal code or zip code, if any.
     * @type {string}
     * @memberof LocationSiteSchemaCommonAllOf
     */
    postcode?: string;
    /**
     * A team associated with the location.
     * @type {string}
     * @memberof LocationSiteSchemaCommonAllOf
     */
    team?: string;
    /**
     * The location\'s telephone number.
     * @type {string}
     * @memberof LocationSiteSchemaCommonAllOf
     */
    phone?: string;
    /**
     * The location\'s email address.
     * @type {string}
     * @memberof LocationSiteSchemaCommonAllOf
     */
    email?: string;
}


