// tslint:disable
/**
 * Invotra API
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CustomContentSchemaUpdateAllOfAttachments } from './custom-content-schema-update-all-of-attachments';
import { CustomContentSchemaUpdateAllOfGrades } from './custom-content-schema-update-all-of-grades';
import { CustomContentSchemaUpdateAllOfLocations } from './custom-content-schema-update-all-of-locations';
import { CustomContentSchemaUpdateAllOfRegions } from './custom-content-schema-update-all-of-regions';
import { PageSchemaUpdateAllOfAuthor } from './page-schema-update-all-of-author';
import { PageSchemaUpdateAllOfImage } from './page-schema-update-all-of-image';
import { PageSchemaUpdateAllOfOwner } from './page-schema-update-all-of-owner';
import { PageSchemaUpdateAllOfSiteSection } from './page-schema-update-all-of-site-section';
import { PageSchemaUpdateAllOfTeam } from './page-schema-update-all-of-team';

/**
 * 
 * @export
 * @interface PageSchemaUpdateAllOf
 */
export interface PageSchemaUpdateAllOf {
    /**
     * 
     * @type {PageSchemaUpdateAllOfSiteSection}
     * @memberof PageSchemaUpdateAllOf
     */
    site_section?: PageSchemaUpdateAllOfSiteSection;
    /**
     * 
     * @type {PageSchemaUpdateAllOfImage}
     * @memberof PageSchemaUpdateAllOf
     */
    image?: PageSchemaUpdateAllOfImage;
    /**
     * 
     * @type {PageSchemaUpdateAllOfAuthor}
     * @memberof PageSchemaUpdateAllOf
     */
    author?: PageSchemaUpdateAllOfAuthor;
    /**
     * The attached files of this page.
     * @type {Array<CustomContentSchemaUpdateAllOfAttachments>}
     * @memberof PageSchemaUpdateAllOf
     */
    attachments?: Array<CustomContentSchemaUpdateAllOfAttachments>;
    /**
     * 
     * @type {PageSchemaUpdateAllOfOwner}
     * @memberof PageSchemaUpdateAllOf
     */
    owner?: PageSchemaUpdateAllOfOwner;
    /**
     * 
     * @type {PageSchemaUpdateAllOfTeam}
     * @memberof PageSchemaUpdateAllOf
     */
    team?: PageSchemaUpdateAllOfTeam;
    /**
     * The locations targeting this page.
     * @type {Array<CustomContentSchemaUpdateAllOfLocations>}
     * @memberof PageSchemaUpdateAllOf
     */
    locations?: Array<CustomContentSchemaUpdateAllOfLocations>;
    /**
     * The grades targeting this page.
     * @type {Array<CustomContentSchemaUpdateAllOfGrades>}
     * @memberof PageSchemaUpdateAllOf
     */
    grades?: Array<CustomContentSchemaUpdateAllOfGrades>;
    /**
     * The regions targeting this page.
     * @type {Array<CustomContentSchemaUpdateAllOfRegions>}
     * @memberof PageSchemaUpdateAllOf
     */
    regions?: Array<CustomContentSchemaUpdateAllOfRegions>;
}


