// tslint:disable
/**
 * InvotraAPI
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The country of this policy.
 * @export
 * @interface PolicySchemaAllOf1Country
 */
export interface PolicySchemaAllOf1Country {
    /**
     * Invotra UUID of the country.
     * @type {string}
     * @memberof PolicySchemaAllOf1Country
     */
    uuid?: string;
    /**
     * This is the name of the country.
     * @type {string}
     * @memberof PolicySchemaAllOf1Country
     */
    name?: string;
}


