// tslint:disable
/**
 * Invotra API
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PolicyTypeSchemaAllOf
 */
export interface PolicyTypeSchemaAllOf {
    /**
     * Invotra UUID of the policy type.
     * @type {string}
     * @memberof PolicyTypeSchemaAllOf
     */
    uuid?: string;
    /**
     * Indicates that this policy type has children.
     * @type {boolean}
     * @memberof PolicyTypeSchemaAllOf
     */
    has_children?: boolean;
}


