// tslint:disable
/**
 * Invotra API
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PostCategorySchema
 */
export interface PostCategorySchema {
    /**
     * Category name
     * @type {string}
     * @memberof PostCategorySchema
     */
    name?: string;
    /**
     * This is the Invotra UUID of the category.
     * @type {string}
     * @memberof PostCategorySchema
     */
    uuid?: string;
    /**
     * Colour of the category. Any CSS colour allowed.
     * @type {string}
     * @memberof PostCategorySchema
     */
    category_colour?: string;
}


