// tslint:disable
/**
 * Invotra API
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CustomContentSchemaUpdateAllOfGrades } from './custom-content-schema-update-all-of-grades';
import { CustomContentSchemaUpdateAllOfLocations } from './custom-content-schema-update-all-of-locations';
import { CustomContentSchemaUpdateAllOfRegions } from './custom-content-schema-update-all-of-regions';
import { PromotionSchemaCreateAllOfAuthor } from './promotion-schema-create-all-of-author';
import { PromotionSchemaUpdateAllOfImage } from './promotion-schema-update-all-of-image';
import { PromotionSchemaUpdateAllOfOwner } from './promotion-schema-update-all-of-owner';
import { PromotionSchemaUpdateAllOfSiteSection } from './promotion-schema-update-all-of-site-section';
import { PromotionSchemaUpdateAllOfTeam } from './promotion-schema-update-all-of-team';

/**
 * 
 * @export
 * @interface PromotionSchemaCreateAllOf
 */
export interface PromotionSchemaCreateAllOf {
    /**
     * 
     * @type {PromotionSchemaUpdateAllOfSiteSection}
     * @memberof PromotionSchemaCreateAllOf
     */
    site_section: PromotionSchemaUpdateAllOfSiteSection;
    /**
     * 
     * @type {PromotionSchemaUpdateAllOfImage}
     * @memberof PromotionSchemaCreateAllOf
     */
    image?: PromotionSchemaUpdateAllOfImage;
    /**
     * 
     * @type {PromotionSchemaUpdateAllOfOwner}
     * @memberof PromotionSchemaCreateAllOf
     */
    owner: PromotionSchemaUpdateAllOfOwner;
    /**
     * 
     * @type {PromotionSchemaCreateAllOfAuthor}
     * @memberof PromotionSchemaCreateAllOf
     */
    author?: PromotionSchemaCreateAllOfAuthor;
    /**
     * 
     * @type {PromotionSchemaUpdateAllOfTeam}
     * @memberof PromotionSchemaCreateAllOf
     */
    team?: PromotionSchemaUpdateAllOfTeam;
    /**
     * The locations targeting this promotion.
     * @type {Array<CustomContentSchemaUpdateAllOfLocations>}
     * @memberof PromotionSchemaCreateAllOf
     */
    locations?: Array<CustomContentSchemaUpdateAllOfLocations>;
    /**
     * The grades targeting this promotion.
     * @type {Array<CustomContentSchemaUpdateAllOfGrades>}
     * @memberof PromotionSchemaCreateAllOf
     */
    grades?: Array<CustomContentSchemaUpdateAllOfGrades>;
    /**
     * The regions targeting this promotion.
     * @type {Array<CustomContentSchemaUpdateAllOfRegions>}
     * @memberof PromotionSchemaCreateAllOf
     */
    regions?: Array<CustomContentSchemaUpdateAllOfRegions>;
}


