// tslint:disable
/**
 * InvotraAPI
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CustomContentSchemaAllOf1Grades } from './custom-content-schema-all-of1-grades';
import { CustomContentSchemaAllOf1Locations } from './custom-content-schema-all-of1-locations';
import { CustomContentSchemaAllOf1Regions } from './custom-content-schema-all-of1-regions';
import { FileSchema } from './file-schema';
import { PromotionSchemaAllOf1SiteSection } from './promotion-schema-all-of1-site-section';
import { PromotionSchemaAllOf1Team } from './promotion-schema-all-of1-team';
import { UserTrimmedSchema } from './user-trimmed-schema';

/**
 * 
 * @export
 * @interface PromotionSchemaAllOf1
 */
export interface PromotionSchemaAllOf1 {
    /**
     * 
     * @type {PromotionSchemaAllOf1SiteSection}
     * @memberof PromotionSchemaAllOf1
     */
    site_section?: PromotionSchemaAllOf1SiteSection;
    /**
     * promotion Image.
     * @type {FileSchema}
     * @memberof PromotionSchemaAllOf1
     */
    image?: FileSchema;
    /**
     * The owner user of the promotion.
     * @type {UserTrimmedSchema}
     * @memberof PromotionSchemaAllOf1
     */
    owner?: UserTrimmedSchema;
    /**
     * The author of this promotion.
     * @type {UserTrimmedSchema}
     * @memberof PromotionSchemaAllOf1
     */
    author?: UserTrimmedSchema;
    /**
     * 
     * @type {PromotionSchemaAllOf1Team}
     * @memberof PromotionSchemaAllOf1
     */
    team?: PromotionSchemaAllOf1Team;
    /**
     * The locations targeting this promotion.
     * @type {Array<CustomContentSchemaAllOf1Locations>}
     * @memberof PromotionSchemaAllOf1
     */
    locations?: Array<CustomContentSchemaAllOf1Locations>;
    /**
     * The grades targeting this promotion.
     * @type {Array<CustomContentSchemaAllOf1Grades>}
     * @memberof PromotionSchemaAllOf1
     */
    grades?: Array<CustomContentSchemaAllOf1Grades>;
    /**
     * The regions targeting this promotion.
     * @type {Array<CustomContentSchemaAllOf1Regions>}
     * @memberof PromotionSchemaAllOf1
     */
    regions?: Array<CustomContentSchemaAllOf1Regions>;
    /**
     * This is the timestamp (in seconds) of when the promotion was created.
     * @type {number}
     * @memberof PromotionSchemaAllOf1
     */
    timestamp_created?: number;
    /**
     * This is the timestamp (in seconds) of when the promotion was last updated.
     * @type {number}
     * @memberof PromotionSchemaAllOf1
     */
    timestamp_updated?: number;
    /**
     * Count of comments on the promotion.
     * @type {number}
     * @memberof PromotionSchemaAllOf1
     */
    comment_count?: number;
    /**
     * Count of likes on the promotion.
     * @type {number}
     * @memberof PromotionSchemaAllOf1
     */
    likes_count?: number;
    /**
     * Published status for the promotion.
     * @type {boolean}
     * @memberof PromotionSchemaAllOf1
     */
    published?: boolean;
}


