// tslint:disable
/**
 * Invotra API
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SecurityClassificationSchemaAllOf
 */
export interface SecurityClassificationSchemaAllOf {
    /**
     * Invotra UUID of the security classification.
     * @type {string}
     * @memberof SecurityClassificationSchemaAllOf
     */
    uuid?: string;
    /**
     * Indicates that this security classification has children.
     * @type {boolean}
     * @memberof SecurityClassificationSchemaAllOf
     */
    has_children?: boolean;
}


