// tslint:disable
/**
 * InvotraAPI
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StatusSchema
 */
export interface StatusSchema {
    /**
     * Status of the API.
     * @type {string}
     * @memberof StatusSchema
     */
    status?: StatusSchemaStatusEnum;
    /**
     * Time on the server as a timestamp (in seconds).
     * @type {number}
     * @memberof StatusSchema
     */
    timestamp?: number;
    /**
     * Time on the server in a human readable format. The format is not guaranteed to be stable; software should read the timestamp field instead.
     * @type {string}
     * @memberof StatusSchema
     */
    datetime?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum StatusSchemaStatusEnum {
    OK = 'OK'
}



