// tslint:disable
/**
 * InvotraAPI
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
import * as globalImportUrl from 'url';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, BaseAPI, RequiredError } from '../base';
/**
 * CountriesApi - axios parameter creator
 * @export
 */
export var CountriesApiAxiosParamCreator = function (configuration) {
    return {
        /**
         * Delete a country.
         * @param {string} country_id The Invotra UUID of the country.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countriesCountryIdDelete: function (country_id, options) {
            if (options === void 0) { options = {}; }
            // verify required parameter 'country_id' is not null or undefined
            if (country_id === null || country_id === undefined) {
                throw new RequiredError('country_id', 'Required parameter country_id was null or undefined when calling countriesCountryIdDelete.');
            }
            var localVarPath = "/countries/{country_id}"
                .replace("{" + "country_id" + "}", encodeURIComponent(String(country_id)));
            var localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            var baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            var localVarRequestOptions = __assign(__assign({ method: 'DELETE' }, baseOptions), options);
            var localVarHeaderParameter = {};
            var localVarQueryParameter = {};
            // authentication APIKeyHeader required
            if (configuration && configuration.apiKey) {
                var localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("X-API-Key")
                    : configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }
            // authentication CognitoJwt required
            // oauth required
            if (configuration && configuration.accessToken) {
                var localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("CognitoJwt", ["invotra/countries:write"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }
            // authentication SessionCookieHeader required
            localVarUrlObj.query = __assign(__assign(__assign({}, localVarUrlObj.query), localVarQueryParameter), options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = __assign(__assign({}, localVarHeaderParameter), options.headers);
            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get information about the country.
         * @param {string} country_id The Invotra UUID of the country.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countriesCountryIdGet: function (country_id, options) {
            if (options === void 0) { options = {}; }
            // verify required parameter 'country_id' is not null or undefined
            if (country_id === null || country_id === undefined) {
                throw new RequiredError('country_id', 'Required parameter country_id was null or undefined when calling countriesCountryIdGet.');
            }
            var localVarPath = "/countries/{country_id}"
                .replace("{" + "country_id" + "}", encodeURIComponent(String(country_id)));
            var localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            var baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            var localVarRequestOptions = __assign(__assign({ method: 'GET' }, baseOptions), options);
            var localVarHeaderParameter = {};
            var localVarQueryParameter = {};
            // authentication APIKeyHeader required
            if (configuration && configuration.apiKey) {
                var localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("X-API-Key")
                    : configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }
            // authentication CognitoJwt required
            // oauth required
            if (configuration && configuration.accessToken) {
                var localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("CognitoJwt", ["invotra/countries:read"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }
            // authentication SessionCookieHeader required
            localVarUrlObj.query = __assign(__assign(__assign({}, localVarUrlObj.query), localVarQueryParameter), options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = __assign(__assign({}, localVarHeaderParameter), options.headers);
            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update country information.
         * @param {string} country_id The Invotra UUID of the country.
         * @param {CountrySchemaCommon} CountrySchemaCommon
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countriesCountryIdPut: function (country_id, CountrySchemaCommon, options) {
            if (options === void 0) { options = {}; }
            // verify required parameter 'country_id' is not null or undefined
            if (country_id === null || country_id === undefined) {
                throw new RequiredError('country_id', 'Required parameter country_id was null or undefined when calling countriesCountryIdPut.');
            }
            // verify required parameter 'CountrySchemaCommon' is not null or undefined
            if (CountrySchemaCommon === null || CountrySchemaCommon === undefined) {
                throw new RequiredError('CountrySchemaCommon', 'Required parameter CountrySchemaCommon was null or undefined when calling countriesCountryIdPut.');
            }
            var localVarPath = "/countries/{country_id}"
                .replace("{" + "country_id" + "}", encodeURIComponent(String(country_id)));
            var localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            var baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            var localVarRequestOptions = __assign(__assign({ method: 'PUT' }, baseOptions), options);
            var localVarHeaderParameter = {};
            var localVarQueryParameter = {};
            // authentication APIKeyHeader required
            if (configuration && configuration.apiKey) {
                var localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("X-API-Key")
                    : configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }
            // authentication CognitoJwt required
            // oauth required
            if (configuration && configuration.accessToken) {
                var localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("CognitoJwt", ["invotra/countries:write"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }
            // authentication SessionCookieHeader required
            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarUrlObj.query = __assign(__assign(__assign({}, localVarUrlObj.query), localVarQueryParameter), options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = __assign(__assign({}, localVarHeaderParameter), options.headers);
            var needsSerialization = (typeof CountrySchemaCommon !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data = needsSerialization ? JSON.stringify(CountrySchemaCommon !== undefined ? CountrySchemaCommon : {}) : (CountrySchemaCommon || "");
            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Search for countries. An empty array is returned if no countries are found.
         * @param {string} [name] Filter by name. Matches on whole words.
         * @param {string} [external_id] Filter by external ID.
         * @param {string} [status] Filter the list of countries on a comma seperated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;, you may inlude both. The default when not supplied is \&quot;published\&quot; only.
         * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the country.
         * @param {number} [offset] The number of items to skip before starting to collect the result set.
         * @param {number} [limit] The numbers of items to return.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countriesListGet: function (name, external_id, status, valid_parents_for, offset, limit, options) {
            if (options === void 0) { options = {}; }
            var localVarPath = "/countries/list";
            var localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            var baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            var localVarRequestOptions = __assign(__assign({ method: 'GET' }, baseOptions), options);
            var localVarHeaderParameter = {};
            var localVarQueryParameter = {};
            // authentication APIKeyHeader required
            if (configuration && configuration.apiKey) {
                var localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("X-API-Key")
                    : configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }
            // authentication CognitoJwt required
            // oauth required
            if (configuration && configuration.accessToken) {
                var localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("CognitoJwt", ["invotra/countries:read"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }
            // authentication SessionCookieHeader required
            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }
            if (external_id !== undefined) {
                localVarQueryParameter['external_id'] = external_id;
            }
            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }
            if (valid_parents_for !== undefined) {
                localVarQueryParameter['valid_parents_for'] = valid_parents_for;
            }
            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }
            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }
            localVarUrlObj.query = __assign(__assign(__assign({}, localVarUrlObj.query), localVarQueryParameter), options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = __assign(__assign({}, localVarHeaderParameter), options.headers);
            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Provision a new country.
         * @param {CountrySchemaCreate} CountrySchemaCreate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countriesPost: function (CountrySchemaCreate, options) {
            if (options === void 0) { options = {}; }
            // verify required parameter 'CountrySchemaCreate' is not null or undefined
            if (CountrySchemaCreate === null || CountrySchemaCreate === undefined) {
                throw new RequiredError('CountrySchemaCreate', 'Required parameter CountrySchemaCreate was null or undefined when calling countriesPost.');
            }
            var localVarPath = "/countries";
            var localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            var baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            var localVarRequestOptions = __assign(__assign({ method: 'POST' }, baseOptions), options);
            var localVarHeaderParameter = {};
            var localVarQueryParameter = {};
            // authentication APIKeyHeader required
            if (configuration && configuration.apiKey) {
                var localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("X-API-Key")
                    : configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }
            // authentication CognitoJwt required
            // oauth required
            if (configuration && configuration.accessToken) {
                var localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("CognitoJwt", ["invotra/countries:write"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }
            // authentication SessionCookieHeader required
            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarUrlObj.query = __assign(__assign(__assign({}, localVarUrlObj.query), localVarQueryParameter), options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = __assign(__assign({}, localVarHeaderParameter), options.headers);
            var needsSerialization = (typeof CountrySchemaCreate !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data = needsSerialization ? JSON.stringify(CountrySchemaCreate !== undefined ? CountrySchemaCreate : {}) : (CountrySchemaCreate || "");
            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    };
};
/**
 * CountriesApi - functional programming interface
 * @export
 */
export var CountriesApiFp = function (configuration) {
    return {
        /**
         * Delete a country.
         * @param {string} country_id The Invotra UUID of the country.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countriesCountryIdDelete: function (country_id, options) {
            var localVarAxiosArgs = CountriesApiAxiosParamCreator(configuration).countriesCountryIdDelete(country_id, options);
            return function (axios, basePath) {
                if (axios === void 0) { axios = globalAxios; }
                if (basePath === void 0) { basePath = BASE_PATH; }
                var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get information about the country.
         * @param {string} country_id The Invotra UUID of the country.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countriesCountryIdGet: function (country_id, options) {
            var localVarAxiosArgs = CountriesApiAxiosParamCreator(configuration).countriesCountryIdGet(country_id, options);
            return function (axios, basePath) {
                if (axios === void 0) { axios = globalAxios; }
                if (basePath === void 0) { basePath = BASE_PATH; }
                var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Update country information.
         * @param {string} country_id The Invotra UUID of the country.
         * @param {CountrySchemaCommon} CountrySchemaCommon
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countriesCountryIdPut: function (country_id, CountrySchemaCommon, options) {
            var localVarAxiosArgs = CountriesApiAxiosParamCreator(configuration).countriesCountryIdPut(country_id, CountrySchemaCommon, options);
            return function (axios, basePath) {
                if (axios === void 0) { axios = globalAxios; }
                if (basePath === void 0) { basePath = BASE_PATH; }
                var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Search for countries. An empty array is returned if no countries are found.
         * @param {string} [name] Filter by name. Matches on whole words.
         * @param {string} [external_id] Filter by external ID.
         * @param {string} [status] Filter the list of countries on a comma seperated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;, you may inlude both. The default when not supplied is \&quot;published\&quot; only.
         * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the country.
         * @param {number} [offset] The number of items to skip before starting to collect the result set.
         * @param {number} [limit] The numbers of items to return.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countriesListGet: function (name, external_id, status, valid_parents_for, offset, limit, options) {
            var localVarAxiosArgs = CountriesApiAxiosParamCreator(configuration).countriesListGet(name, external_id, status, valid_parents_for, offset, limit, options);
            return function (axios, basePath) {
                if (axios === void 0) { axios = globalAxios; }
                if (basePath === void 0) { basePath = BASE_PATH; }
                var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Provision a new country.
         * @param {CountrySchemaCreate} CountrySchemaCreate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countriesPost: function (CountrySchemaCreate, options) {
            var localVarAxiosArgs = CountriesApiAxiosParamCreator(configuration).countriesPost(CountrySchemaCreate, options);
            return function (axios, basePath) {
                if (axios === void 0) { axios = globalAxios; }
                if (basePath === void 0) { basePath = BASE_PATH; }
                var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
    };
};
/**
 * CountriesApi - factory interface
 * @export
 */
export var CountriesApiFactory = function (configuration, basePath, axios) {
    return {
        /**
         * Delete a country.
         * @param {string} country_id The Invotra UUID of the country.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countriesCountryIdDelete: function (country_id, options) {
            return CountriesApiFp(configuration).countriesCountryIdDelete(country_id, options)(axios, basePath);
        },
        /**
         * Get information about the country.
         * @param {string} country_id The Invotra UUID of the country.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countriesCountryIdGet: function (country_id, options) {
            return CountriesApiFp(configuration).countriesCountryIdGet(country_id, options)(axios, basePath);
        },
        /**
         * Update country information.
         * @param {string} country_id The Invotra UUID of the country.
         * @param {CountrySchemaCommon} CountrySchemaCommon
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countriesCountryIdPut: function (country_id, CountrySchemaCommon, options) {
            return CountriesApiFp(configuration).countriesCountryIdPut(country_id, CountrySchemaCommon, options)(axios, basePath);
        },
        /**
         * Search for countries. An empty array is returned if no countries are found.
         * @param {string} [name] Filter by name. Matches on whole words.
         * @param {string} [external_id] Filter by external ID.
         * @param {string} [status] Filter the list of countries on a comma seperated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;, you may inlude both. The default when not supplied is \&quot;published\&quot; only.
         * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the country.
         * @param {number} [offset] The number of items to skip before starting to collect the result set.
         * @param {number} [limit] The numbers of items to return.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countriesListGet: function (name, external_id, status, valid_parents_for, offset, limit, options) {
            return CountriesApiFp(configuration).countriesListGet(name, external_id, status, valid_parents_for, offset, limit, options)(axios, basePath);
        },
        /**
         * Provision a new country.
         * @param {CountrySchemaCreate} CountrySchemaCreate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countriesPost: function (CountrySchemaCreate, options) {
            return CountriesApiFp(configuration).countriesPost(CountrySchemaCreate, options)(axios, basePath);
        },
    };
};
/**
 * CountriesApi - object-oriented interface
 * @export
 * @class CountriesApi
 * @extends {BaseAPI}
 */
var CountriesApi = /** @class */ (function (_super) {
    __extends(CountriesApi, _super);
    function CountriesApi() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    /**
     * Delete a country.
     * @param {string} country_id The Invotra UUID of the country.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CountriesApi
     */
    CountriesApi.prototype.countriesCountryIdDelete = function (country_id, options) {
        return CountriesApiFp(this.configuration).countriesCountryIdDelete(country_id, options)(this.axios, this.basePath);
    };
    /**
     * Get information about the country.
     * @param {string} country_id The Invotra UUID of the country.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CountriesApi
     */
    CountriesApi.prototype.countriesCountryIdGet = function (country_id, options) {
        return CountriesApiFp(this.configuration).countriesCountryIdGet(country_id, options)(this.axios, this.basePath);
    };
    /**
     * Update country information.
     * @param {string} country_id The Invotra UUID of the country.
     * @param {CountrySchemaCommon} CountrySchemaCommon
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CountriesApi
     */
    CountriesApi.prototype.countriesCountryIdPut = function (country_id, CountrySchemaCommon, options) {
        return CountriesApiFp(this.configuration).countriesCountryIdPut(country_id, CountrySchemaCommon, options)(this.axios, this.basePath);
    };
    /**
     * Search for countries. An empty array is returned if no countries are found.
     * @param {string} [name] Filter by name. Matches on whole words.
     * @param {string} [external_id] Filter by external ID.
     * @param {string} [status] Filter the list of countries on a comma seperated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;, you may inlude both. The default when not supplied is \&quot;published\&quot; only.
     * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the country.
     * @param {number} [offset] The number of items to skip before starting to collect the result set.
     * @param {number} [limit] The numbers of items to return.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CountriesApi
     */
    CountriesApi.prototype.countriesListGet = function (name, external_id, status, valid_parents_for, offset, limit, options) {
        return CountriesApiFp(this.configuration).countriesListGet(name, external_id, status, valid_parents_for, offset, limit, options)(this.axios, this.basePath);
    };
    /**
     * Provision a new country.
     * @param {CountrySchemaCreate} CountrySchemaCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CountriesApi
     */
    CountriesApi.prototype.countriesPost = function (CountrySchemaCreate, options) {
        return CountriesApiFp(this.configuration).countriesPost(CountrySchemaCreate, options)(this.axios, this.basePath);
    };
    return CountriesApi;
}(BaseAPI));
export { CountriesApi };
//# sourceMappingURL=countries-api.js.map