// tslint:disable
/**
 * Invotra API
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
import * as globalImportUrl from 'url';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, BaseAPI, RequiredError } from '../base';
/**
 * PagesApi - axios parameter creator
 * @export
 */
export var PagesApiAxiosParamCreator = function (configuration) {
    return {
        /**
         * Search for pages. An empty array is returned if no pages where found.
         * @param {string} [author_uuid] Filter on Invotra UUID of the author.
         * @param {string} [created_date] Filter on date created. Format: YYYY-MM-DD.
         * @param {string} [updated_date] Filter on date updated. Format: YYYY-MM-DD.
         * @param {string} [external_id] Filter by external ID.
         * @param {string} [state] Filter the list of custom content on a comma-separated list of states. Valid statuses are \&quot;draft\&quot;, \&quot;needs_review\&quot;, \&quot;reviewed\&quot;, \&quot;published\&quot;, and \&quot;unpublished\&quot;. You may include multiple. The default when not supplied is \&quot;published\&quot; only.
         * @param {'timestamp_created' | 'timestamp_updated'} [sort] Field to sort by.
         * @param {'asc' | 'desc'} [order] Sort order.
         * @param {number} [offset] The number of items to skip before starting to collect the result set.
         * @param {number} [limit] The numbers of items to return. If the value specified is more than the maximum, the result count will be limited to the maximum.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pagesListGet: function (author_uuid, created_date, updated_date, external_id, state, sort, order, offset, limit, options) {
            if (options === void 0) { options = {}; }
            var localVarPath = "/pages/list";
            var localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            var baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            var localVarRequestOptions = __assign(__assign({ method: 'GET' }, baseOptions), options);
            var localVarHeaderParameter = {};
            var localVarQueryParameter = {};
            // authentication APIKeyHeader required
            if (configuration && configuration.apiKey) {
                var localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("X-API-Key")
                    : configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }
            // authentication CognitoJwt required
            // oauth required
            if (configuration && configuration.accessToken) {
                var localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("CognitoJwt", ["invotra/pages:read"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }
            // authentication SessionCookieHeader required
            if (author_uuid !== undefined) {
                localVarQueryParameter['author_uuid'] = author_uuid;
            }
            if (created_date !== undefined) {
                localVarQueryParameter['created_date'] = created_date;
            }
            if (updated_date !== undefined) {
                localVarQueryParameter['updated_date'] = updated_date;
            }
            if (external_id !== undefined) {
                localVarQueryParameter['external_id'] = external_id;
            }
            if (state !== undefined) {
                localVarQueryParameter['state'] = state;
            }
            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }
            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }
            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }
            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }
            localVarUrlObj.query = __assign(__assign(__assign({}, localVarUrlObj.query), localVarQueryParameter), options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = __assign(__assign({}, localVarHeaderParameter), options.headers);
            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a page.
         * @param {string} page_id The Invotra UUID of the page.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pagesPageIdDelete: function (page_id, options) {
            if (options === void 0) { options = {}; }
            // verify required parameter 'page_id' is not null or undefined
            if (page_id === null || page_id === undefined) {
                throw new RequiredError('page_id', 'Required parameter page_id was null or undefined when calling pagesPageIdDelete.');
            }
            var localVarPath = "/pages/{page_id}"
                .replace("{" + "page_id" + "}", encodeURIComponent(String(page_id)));
            var localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            var baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            var localVarRequestOptions = __assign(__assign({ method: 'DELETE' }, baseOptions), options);
            var localVarHeaderParameter = {};
            var localVarQueryParameter = {};
            // authentication APIKeyHeader required
            if (configuration && configuration.apiKey) {
                var localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("X-API-Key")
                    : configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }
            // authentication CognitoJwt required
            // oauth required
            if (configuration && configuration.accessToken) {
                var localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("CognitoJwt", ["invotra/pages:write"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }
            // authentication SessionCookieHeader required
            localVarUrlObj.query = __assign(__assign(__assign({}, localVarUrlObj.query), localVarQueryParameter), options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = __assign(__assign({}, localVarHeaderParameter), options.headers);
            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get information about the page.
         * @param {string} page_id The Invotra UUID of the page.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pagesPageIdGet: function (page_id, options) {
            if (options === void 0) { options = {}; }
            // verify required parameter 'page_id' is not null or undefined
            if (page_id === null || page_id === undefined) {
                throw new RequiredError('page_id', 'Required parameter page_id was null or undefined when calling pagesPageIdGet.');
            }
            var localVarPath = "/pages/{page_id}"
                .replace("{" + "page_id" + "}", encodeURIComponent(String(page_id)));
            var localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            var baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            var localVarRequestOptions = __assign(__assign({ method: 'GET' }, baseOptions), options);
            var localVarHeaderParameter = {};
            var localVarQueryParameter = {};
            // authentication APIKeyHeader required
            if (configuration && configuration.apiKey) {
                var localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("X-API-Key")
                    : configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }
            // authentication CognitoJwt required
            // oauth required
            if (configuration && configuration.accessToken) {
                var localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("CognitoJwt", ["invotra/pages:read"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }
            // authentication SessionCookieHeader required
            localVarUrlObj.query = __assign(__assign(__assign({}, localVarUrlObj.query), localVarQueryParameter), options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = __assign(__assign({}, localVarHeaderParameter), options.headers);
            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update page information.
         * @param {string} page_id The Invotra UUID of the page.
         * @param {PageSchemaUpdate} PageSchemaUpdate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pagesPageIdPut: function (page_id, PageSchemaUpdate, options) {
            if (options === void 0) { options = {}; }
            // verify required parameter 'page_id' is not null or undefined
            if (page_id === null || page_id === undefined) {
                throw new RequiredError('page_id', 'Required parameter page_id was null or undefined when calling pagesPageIdPut.');
            }
            // verify required parameter 'PageSchemaUpdate' is not null or undefined
            if (PageSchemaUpdate === null || PageSchemaUpdate === undefined) {
                throw new RequiredError('PageSchemaUpdate', 'Required parameter PageSchemaUpdate was null or undefined when calling pagesPageIdPut.');
            }
            var localVarPath = "/pages/{page_id}"
                .replace("{" + "page_id" + "}", encodeURIComponent(String(page_id)));
            var localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            var baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            var localVarRequestOptions = __assign(__assign({ method: 'PUT' }, baseOptions), options);
            var localVarHeaderParameter = {};
            var localVarQueryParameter = {};
            // authentication APIKeyHeader required
            if (configuration && configuration.apiKey) {
                var localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("X-API-Key")
                    : configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }
            // authentication CognitoJwt required
            // oauth required
            if (configuration && configuration.accessToken) {
                var localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("CognitoJwt", ["invotra/pages:write"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }
            // authentication SessionCookieHeader required
            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarUrlObj.query = __assign(__assign(__assign({}, localVarUrlObj.query), localVarQueryParameter), options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = __assign(__assign({}, localVarHeaderParameter), options.headers);
            var needsSerialization = (typeof PageSchemaUpdate !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data = needsSerialization ? JSON.stringify(PageSchemaUpdate !== undefined ? PageSchemaUpdate : {}) : (PageSchemaUpdate || "");
            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Provision a new page.
         * @param {PageSchemaCreate} PageSchemaCreate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pagesPost: function (PageSchemaCreate, options) {
            if (options === void 0) { options = {}; }
            // verify required parameter 'PageSchemaCreate' is not null or undefined
            if (PageSchemaCreate === null || PageSchemaCreate === undefined) {
                throw new RequiredError('PageSchemaCreate', 'Required parameter PageSchemaCreate was null or undefined when calling pagesPost.');
            }
            var localVarPath = "/pages";
            var localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            var baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            var localVarRequestOptions = __assign(__assign({ method: 'POST' }, baseOptions), options);
            var localVarHeaderParameter = {};
            var localVarQueryParameter = {};
            // authentication APIKeyHeader required
            if (configuration && configuration.apiKey) {
                var localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("X-API-Key")
                    : configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }
            // authentication CognitoJwt required
            // oauth required
            if (configuration && configuration.accessToken) {
                var localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("CognitoJwt", ["invotra/pages:write"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }
            // authentication SessionCookieHeader required
            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarUrlObj.query = __assign(__assign(__assign({}, localVarUrlObj.query), localVarQueryParameter), options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = __assign(__assign({}, localVarHeaderParameter), options.headers);
            var needsSerialization = (typeof PageSchemaCreate !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data = needsSerialization ? JSON.stringify(PageSchemaCreate !== undefined ? PageSchemaCreate : {}) : (PageSchemaCreate || "");
            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    };
};
/**
 * PagesApi - functional programming interface
 * @export
 */
export var PagesApiFp = function (configuration) {
    return {
        /**
         * Search for pages. An empty array is returned if no pages where found.
         * @param {string} [author_uuid] Filter on Invotra UUID of the author.
         * @param {string} [created_date] Filter on date created. Format: YYYY-MM-DD.
         * @param {string} [updated_date] Filter on date updated. Format: YYYY-MM-DD.
         * @param {string} [external_id] Filter by external ID.
         * @param {string} [state] Filter the list of custom content on a comma-separated list of states. Valid statuses are \&quot;draft\&quot;, \&quot;needs_review\&quot;, \&quot;reviewed\&quot;, \&quot;published\&quot;, and \&quot;unpublished\&quot;. You may include multiple. The default when not supplied is \&quot;published\&quot; only.
         * @param {'timestamp_created' | 'timestamp_updated'} [sort] Field to sort by.
         * @param {'asc' | 'desc'} [order] Sort order.
         * @param {number} [offset] The number of items to skip before starting to collect the result set.
         * @param {number} [limit] The numbers of items to return. If the value specified is more than the maximum, the result count will be limited to the maximum.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pagesListGet: function (author_uuid, created_date, updated_date, external_id, state, sort, order, offset, limit, options) {
            var localVarAxiosArgs = PagesApiAxiosParamCreator(configuration).pagesListGet(author_uuid, created_date, updated_date, external_id, state, sort, order, offset, limit, options);
            return function (axios, basePath) {
                if (axios === void 0) { axios = globalAxios; }
                if (basePath === void 0) { basePath = BASE_PATH; }
                var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Delete a page.
         * @param {string} page_id The Invotra UUID of the page.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pagesPageIdDelete: function (page_id, options) {
            var localVarAxiosArgs = PagesApiAxiosParamCreator(configuration).pagesPageIdDelete(page_id, options);
            return function (axios, basePath) {
                if (axios === void 0) { axios = globalAxios; }
                if (basePath === void 0) { basePath = BASE_PATH; }
                var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get information about the page.
         * @param {string} page_id The Invotra UUID of the page.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pagesPageIdGet: function (page_id, options) {
            var localVarAxiosArgs = PagesApiAxiosParamCreator(configuration).pagesPageIdGet(page_id, options);
            return function (axios, basePath) {
                if (axios === void 0) { axios = globalAxios; }
                if (basePath === void 0) { basePath = BASE_PATH; }
                var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Update page information.
         * @param {string} page_id The Invotra UUID of the page.
         * @param {PageSchemaUpdate} PageSchemaUpdate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pagesPageIdPut: function (page_id, PageSchemaUpdate, options) {
            var localVarAxiosArgs = PagesApiAxiosParamCreator(configuration).pagesPageIdPut(page_id, PageSchemaUpdate, options);
            return function (axios, basePath) {
                if (axios === void 0) { axios = globalAxios; }
                if (basePath === void 0) { basePath = BASE_PATH; }
                var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Provision a new page.
         * @param {PageSchemaCreate} PageSchemaCreate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pagesPost: function (PageSchemaCreate, options) {
            var localVarAxiosArgs = PagesApiAxiosParamCreator(configuration).pagesPost(PageSchemaCreate, options);
            return function (axios, basePath) {
                if (axios === void 0) { axios = globalAxios; }
                if (basePath === void 0) { basePath = BASE_PATH; }
                var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
    };
};
/**
 * PagesApi - factory interface
 * @export
 */
export var PagesApiFactory = function (configuration, basePath, axios) {
    return {
        /**
         * Search for pages. An empty array is returned if no pages where found.
         * @param {string} [author_uuid] Filter on Invotra UUID of the author.
         * @param {string} [created_date] Filter on date created. Format: YYYY-MM-DD.
         * @param {string} [updated_date] Filter on date updated. Format: YYYY-MM-DD.
         * @param {string} [external_id] Filter by external ID.
         * @param {string} [state] Filter the list of custom content on a comma-separated list of states. Valid statuses are \&quot;draft\&quot;, \&quot;needs_review\&quot;, \&quot;reviewed\&quot;, \&quot;published\&quot;, and \&quot;unpublished\&quot;. You may include multiple. The default when not supplied is \&quot;published\&quot; only.
         * @param {'timestamp_created' | 'timestamp_updated'} [sort] Field to sort by.
         * @param {'asc' | 'desc'} [order] Sort order.
         * @param {number} [offset] The number of items to skip before starting to collect the result set.
         * @param {number} [limit] The numbers of items to return. If the value specified is more than the maximum, the result count will be limited to the maximum.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pagesListGet: function (author_uuid, created_date, updated_date, external_id, state, sort, order, offset, limit, options) {
            return PagesApiFp(configuration).pagesListGet(author_uuid, created_date, updated_date, external_id, state, sort, order, offset, limit, options)(axios, basePath);
        },
        /**
         * Delete a page.
         * @param {string} page_id The Invotra UUID of the page.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pagesPageIdDelete: function (page_id, options) {
            return PagesApiFp(configuration).pagesPageIdDelete(page_id, options)(axios, basePath);
        },
        /**
         * Get information about the page.
         * @param {string} page_id The Invotra UUID of the page.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pagesPageIdGet: function (page_id, options) {
            return PagesApiFp(configuration).pagesPageIdGet(page_id, options)(axios, basePath);
        },
        /**
         * Update page information.
         * @param {string} page_id The Invotra UUID of the page.
         * @param {PageSchemaUpdate} PageSchemaUpdate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pagesPageIdPut: function (page_id, PageSchemaUpdate, options) {
            return PagesApiFp(configuration).pagesPageIdPut(page_id, PageSchemaUpdate, options)(axios, basePath);
        },
        /**
         * Provision a new page.
         * @param {PageSchemaCreate} PageSchemaCreate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pagesPost: function (PageSchemaCreate, options) {
            return PagesApiFp(configuration).pagesPost(PageSchemaCreate, options)(axios, basePath);
        },
    };
};
/**
 * PagesApi - object-oriented interface
 * @export
 * @class PagesApi
 * @extends {BaseAPI}
 */
var PagesApi = /** @class */ (function (_super) {
    __extends(PagesApi, _super);
    function PagesApi() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    /**
     * Search for pages. An empty array is returned if no pages where found.
     * @param {string} [author_uuid] Filter on Invotra UUID of the author.
     * @param {string} [created_date] Filter on date created. Format: YYYY-MM-DD.
     * @param {string} [updated_date] Filter on date updated. Format: YYYY-MM-DD.
     * @param {string} [external_id] Filter by external ID.
     * @param {string} [state] Filter the list of custom content on a comma-separated list of states. Valid statuses are \&quot;draft\&quot;, \&quot;needs_review\&quot;, \&quot;reviewed\&quot;, \&quot;published\&quot;, and \&quot;unpublished\&quot;. You may include multiple. The default when not supplied is \&quot;published\&quot; only.
     * @param {'timestamp_created' | 'timestamp_updated'} [sort] Field to sort by.
     * @param {'asc' | 'desc'} [order] Sort order.
     * @param {number} [offset] The number of items to skip before starting to collect the result set.
     * @param {number} [limit] The numbers of items to return. If the value specified is more than the maximum, the result count will be limited to the maximum.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PagesApi
     */
    PagesApi.prototype.pagesListGet = function (author_uuid, created_date, updated_date, external_id, state, sort, order, offset, limit, options) {
        return PagesApiFp(this.configuration).pagesListGet(author_uuid, created_date, updated_date, external_id, state, sort, order, offset, limit, options)(this.axios, this.basePath);
    };
    /**
     * Delete a page.
     * @param {string} page_id The Invotra UUID of the page.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PagesApi
     */
    PagesApi.prototype.pagesPageIdDelete = function (page_id, options) {
        return PagesApiFp(this.configuration).pagesPageIdDelete(page_id, options)(this.axios, this.basePath);
    };
    /**
     * Get information about the page.
     * @param {string} page_id The Invotra UUID of the page.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PagesApi
     */
    PagesApi.prototype.pagesPageIdGet = function (page_id, options) {
        return PagesApiFp(this.configuration).pagesPageIdGet(page_id, options)(this.axios, this.basePath);
    };
    /**
     * Update page information.
     * @param {string} page_id The Invotra UUID of the page.
     * @param {PageSchemaUpdate} PageSchemaUpdate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PagesApi
     */
    PagesApi.prototype.pagesPageIdPut = function (page_id, PageSchemaUpdate, options) {
        return PagesApiFp(this.configuration).pagesPageIdPut(page_id, PageSchemaUpdate, options)(this.axios, this.basePath);
    };
    /**
     * Provision a new page.
     * @param {PageSchemaCreate} PageSchemaCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PagesApi
     */
    PagesApi.prototype.pagesPost = function (PageSchemaCreate, options) {
        return PagesApiFp(this.configuration).pagesPost(PageSchemaCreate, options)(this.axios, this.basePath);
    };
    return PagesApi;
}(BaseAPI));
export { PagesApi };
//# sourceMappingURL=pages-api.js.map