/**
 * InvotraAPI
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
import { RequestArgs, BaseAPI } from '../base';
import { InlineResponse20050 } from '../model';
import { SearchHighlightSchema } from '../model';
import { SearchHighlightSchemaCommon } from '../model';
import { SearchHighlightSchemaCreate } from '../model';
import { SuccessfulPostResponseSchema } from '../model';
/**
 * SearchHighlightsApi - axios parameter creator
 * @export
 */
export declare const SearchHighlightsApiAxiosParamCreator: (configuration?: Configuration | undefined) => {
    /**
     * Search for search highlights. An empty array is returned if no search highlights are found.
     * @param {string} [name] Filter by name. Matches on whole words.
     * @param {string} [external_id] Filter by external ID.
     * @param {string} [status] Filter the list of search highlights on a comma seperated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;, you may inlude both. The default when not supplied is \&quot;published\&quot; only.
     * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the search highlight.
     * @param {number} [offset] The number of items to skip before starting to collect the result set.
     * @param {number} [limit] The numbers of items to return. If the value specified is more than the maximum, the result count will be limited to the maximum.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchHighlightsListGet(name?: string | undefined, external_id?: string | undefined, status?: string | undefined, valid_parents_for?: string | undefined, offset?: number | undefined, limit?: number | undefined, options?: any): RequestArgs;
    /**
     * Provision a new search highlight.
     * @param {SearchHighlightSchemaCreate} SearchHighlightSchemaCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchHighlightsPost(SearchHighlightSchemaCreate: SearchHighlightSchemaCreate, options?: any): RequestArgs;
    /**
     * Delete a search highlight.
     * @param {string} search_highlight_id The Invotra UUID of the search highlight.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchHighlightsSearchHighlightIdDelete(search_highlight_id: string, options?: any): RequestArgs;
    /**
     * Get information about the search highlight.
     * @param {string} search_highlight_id The Invotra UUID of the search highlight.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchHighlightsSearchHighlightIdGet(search_highlight_id: string, options?: any): RequestArgs;
    /**
     * Update search highlight information.
     * @param {string} search_highlight_id The Invotra UUID of the search highlight.
     * @param {SearchHighlightSchemaCommon} SearchHighlightSchemaCommon
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchHighlightsSearchHighlightIdPut(search_highlight_id: string, SearchHighlightSchemaCommon: SearchHighlightSchemaCommon, options?: any): RequestArgs;
};
/**
 * SearchHighlightsApi - functional programming interface
 * @export
 */
export declare const SearchHighlightsApiFp: (configuration?: Configuration | undefined) => {
    /**
     * Search for search highlights. An empty array is returned if no search highlights are found.
     * @param {string} [name] Filter by name. Matches on whole words.
     * @param {string} [external_id] Filter by external ID.
     * @param {string} [status] Filter the list of search highlights on a comma seperated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;, you may inlude both. The default when not supplied is \&quot;published\&quot; only.
     * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the search highlight.
     * @param {number} [offset] The number of items to skip before starting to collect the result set.
     * @param {number} [limit] The numbers of items to return. If the value specified is more than the maximum, the result count will be limited to the maximum.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchHighlightsListGet(name?: string | undefined, external_id?: string | undefined, status?: string | undefined, valid_parents_for?: string | undefined, offset?: number | undefined, limit?: number | undefined, options?: any): (axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<InlineResponse20050>;
    /**
     * Provision a new search highlight.
     * @param {SearchHighlightSchemaCreate} SearchHighlightSchemaCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchHighlightsPost(SearchHighlightSchemaCreate: SearchHighlightSchemaCreate, options?: any): (axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<SuccessfulPostResponseSchema>;
    /**
     * Delete a search highlight.
     * @param {string} search_highlight_id The Invotra UUID of the search highlight.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchHighlightsSearchHighlightIdDelete(search_highlight_id: string, options?: any): (axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>;
    /**
     * Get information about the search highlight.
     * @param {string} search_highlight_id The Invotra UUID of the search highlight.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchHighlightsSearchHighlightIdGet(search_highlight_id: string, options?: any): (axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<SearchHighlightSchema>;
    /**
     * Update search highlight information.
     * @param {string} search_highlight_id The Invotra UUID of the search highlight.
     * @param {SearchHighlightSchemaCommon} SearchHighlightSchemaCommon
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchHighlightsSearchHighlightIdPut(search_highlight_id: string, SearchHighlightSchemaCommon: SearchHighlightSchemaCommon, options?: any): (axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>;
};
/**
 * SearchHighlightsApi - factory interface
 * @export
 */
export declare const SearchHighlightsApiFactory: (configuration?: Configuration | undefined, basePath?: string | undefined, axios?: AxiosInstance | undefined) => {
    /**
     * Search for search highlights. An empty array is returned if no search highlights are found.
     * @param {string} [name] Filter by name. Matches on whole words.
     * @param {string} [external_id] Filter by external ID.
     * @param {string} [status] Filter the list of search highlights on a comma seperated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;, you may inlude both. The default when not supplied is \&quot;published\&quot; only.
     * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the search highlight.
     * @param {number} [offset] The number of items to skip before starting to collect the result set.
     * @param {number} [limit] The numbers of items to return. If the value specified is more than the maximum, the result count will be limited to the maximum.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchHighlightsListGet(name?: string | undefined, external_id?: string | undefined, status?: string | undefined, valid_parents_for?: string | undefined, offset?: number | undefined, limit?: number | undefined, options?: any): AxiosPromise<InlineResponse20050>;
    /**
     * Provision a new search highlight.
     * @param {SearchHighlightSchemaCreate} SearchHighlightSchemaCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchHighlightsPost(SearchHighlightSchemaCreate: SearchHighlightSchemaCreate, options?: any): AxiosPromise<SuccessfulPostResponseSchema>;
    /**
     * Delete a search highlight.
     * @param {string} search_highlight_id The Invotra UUID of the search highlight.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchHighlightsSearchHighlightIdDelete(search_highlight_id: string, options?: any): AxiosPromise<void>;
    /**
     * Get information about the search highlight.
     * @param {string} search_highlight_id The Invotra UUID of the search highlight.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchHighlightsSearchHighlightIdGet(search_highlight_id: string, options?: any): AxiosPromise<SearchHighlightSchema>;
    /**
     * Update search highlight information.
     * @param {string} search_highlight_id The Invotra UUID of the search highlight.
     * @param {SearchHighlightSchemaCommon} SearchHighlightSchemaCommon
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchHighlightsSearchHighlightIdPut(search_highlight_id: string, SearchHighlightSchemaCommon: SearchHighlightSchemaCommon, options?: any): AxiosPromise<void>;
};
/**
 * SearchHighlightsApi - interface
 * @export
 * @interface SearchHighlightsApi
 */
export interface SearchHighlightsApiInterface {
    /**
     * Search for search highlights. An empty array is returned if no search highlights are found.
     * @param {string} [name] Filter by name. Matches on whole words.
     * @param {string} [external_id] Filter by external ID.
     * @param {string} [status] Filter the list of search highlights on a comma seperated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;, you may inlude both. The default when not supplied is \&quot;published\&quot; only.
     * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the search highlight.
     * @param {number} [offset] The number of items to skip before starting to collect the result set.
     * @param {number} [limit] The numbers of items to return. If the value specified is more than the maximum, the result count will be limited to the maximum.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchHighlightsApiInterface
     */
    searchHighlightsListGet(name?: string, external_id?: string, status?: string, valid_parents_for?: string, offset?: number, limit?: number, options?: any): AxiosPromise<InlineResponse20050>;
    /**
     * Provision a new search highlight.
     * @param {SearchHighlightSchemaCreate} SearchHighlightSchemaCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchHighlightsApiInterface
     */
    searchHighlightsPost(SearchHighlightSchemaCreate: SearchHighlightSchemaCreate, options?: any): AxiosPromise<SuccessfulPostResponseSchema>;
    /**
     * Delete a search highlight.
     * @param {string} search_highlight_id The Invotra UUID of the search highlight.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchHighlightsApiInterface
     */
    searchHighlightsSearchHighlightIdDelete(search_highlight_id: string, options?: any): AxiosPromise<void>;
    /**
     * Get information about the search highlight.
     * @param {string} search_highlight_id The Invotra UUID of the search highlight.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchHighlightsApiInterface
     */
    searchHighlightsSearchHighlightIdGet(search_highlight_id: string, options?: any): AxiosPromise<SearchHighlightSchema>;
    /**
     * Update search highlight information.
     * @param {string} search_highlight_id The Invotra UUID of the search highlight.
     * @param {SearchHighlightSchemaCommon} SearchHighlightSchemaCommon
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchHighlightsApiInterface
     */
    searchHighlightsSearchHighlightIdPut(search_highlight_id: string, SearchHighlightSchemaCommon: SearchHighlightSchemaCommon, options?: any): AxiosPromise<void>;
}
/**
 * SearchHighlightsApi - object-oriented interface
 * @export
 * @class SearchHighlightsApi
 * @extends {BaseAPI}
 */
export declare class SearchHighlightsApi extends BaseAPI implements SearchHighlightsApiInterface {
    /**
     * Search for search highlights. An empty array is returned if no search highlights are found.
     * @param {string} [name] Filter by name. Matches on whole words.
     * @param {string} [external_id] Filter by external ID.
     * @param {string} [status] Filter the list of search highlights on a comma seperated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;, you may inlude both. The default when not supplied is \&quot;published\&quot; only.
     * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the search highlight.
     * @param {number} [offset] The number of items to skip before starting to collect the result set.
     * @param {number} [limit] The numbers of items to return. If the value specified is more than the maximum, the result count will be limited to the maximum.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchHighlightsApi
     */
    searchHighlightsListGet(name?: string, external_id?: string, status?: string, valid_parents_for?: string, offset?: number, limit?: number, options?: any): AxiosPromise<InlineResponse20050>;
    /**
     * Provision a new search highlight.
     * @param {SearchHighlightSchemaCreate} SearchHighlightSchemaCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchHighlightsApi
     */
    searchHighlightsPost(SearchHighlightSchemaCreate: SearchHighlightSchemaCreate, options?: any): AxiosPromise<SuccessfulPostResponseSchema>;
    /**
     * Delete a search highlight.
     * @param {string} search_highlight_id The Invotra UUID of the search highlight.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchHighlightsApi
     */
    searchHighlightsSearchHighlightIdDelete(search_highlight_id: string, options?: any): AxiosPromise<void>;
    /**
     * Get information about the search highlight.
     * @param {string} search_highlight_id The Invotra UUID of the search highlight.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchHighlightsApi
     */
    searchHighlightsSearchHighlightIdGet(search_highlight_id: string, options?: any): AxiosPromise<SearchHighlightSchema>;
    /**
     * Update search highlight information.
     * @param {string} search_highlight_id The Invotra UUID of the search highlight.
     * @param {SearchHighlightSchemaCommon} SearchHighlightSchemaCommon
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchHighlightsApi
     */
    searchHighlightsSearchHighlightIdPut(search_highlight_id: string, SearchHighlightSchemaCommon: SearchHighlightSchemaCommon, options?: any): AxiosPromise<void>;
}
