/**
 * Invotra API
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
import { RequestArgs, BaseAPI } from '../base';
import { InlineResponse20051 } from '../model';
import { SecurityClassificationSchema } from '../model';
import { SecurityClassificationSchemaCommon } from '../model';
import { SecurityClassificationSchemaCreate } from '../model';
import { SuccessfulPostResponseSchema } from '../model';
/**
 * SecurityClassificationsApi - axios parameter creator
 * @export
 */
export declare const SecurityClassificationsApiAxiosParamCreator: (configuration?: Configuration | undefined) => {
    /**
     * Search for security classifications. An empty array is returned if no security classifications are found.
     * @param {string} [name] Filter by name. Matches on whole words.
     * @param {string} [external_id] Filter by external ID.
     * @param {string} [status] Filter the list of security classifications on a comma-separated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;. You may include both. The default when not supplied is \&quot;published\&quot; only.
     * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the security classification.
     * @param {number} [offset] The number of items to skip before starting to collect the result set.
     * @param {number} [limit] The numbers of items to return. If the value specified is more than the maximum, the result count will be limited to the maximum.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    securityClassificationsListGet(name?: string | undefined, external_id?: string | undefined, status?: string | undefined, valid_parents_for?: string | undefined, offset?: number | undefined, limit?: number | undefined, options?: any): RequestArgs;
    /**
     * Provision a new security classification.
     * @param {SecurityClassificationSchemaCreate} SecurityClassificationSchemaCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    securityClassificationsPost(SecurityClassificationSchemaCreate: SecurityClassificationSchemaCreate, options?: any): RequestArgs;
    /**
     * Delete a security classification.
     * @param {string} security_classification_id The Invotra UUID of the security classification.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    securityClassificationsSecurityClassificationIdDelete(security_classification_id: string, options?: any): RequestArgs;
    /**
     * Get information about the security classification.
     * @param {string} security_classification_id The Invotra UUID of the security classification.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    securityClassificationsSecurityClassificationIdGet(security_classification_id: string, options?: any): RequestArgs;
    /**
     * Update security classification information.
     * @param {string} security_classification_id The Invotra UUID of the security classification.
     * @param {SecurityClassificationSchemaCommon} SecurityClassificationSchemaCommon
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    securityClassificationsSecurityClassificationIdPut(security_classification_id: string, SecurityClassificationSchemaCommon: SecurityClassificationSchemaCommon, options?: any): RequestArgs;
};
/**
 * SecurityClassificationsApi - functional programming interface
 * @export
 */
export declare const SecurityClassificationsApiFp: (configuration?: Configuration | undefined) => {
    /**
     * Search for security classifications. An empty array is returned if no security classifications are found.
     * @param {string} [name] Filter by name. Matches on whole words.
     * @param {string} [external_id] Filter by external ID.
     * @param {string} [status] Filter the list of security classifications on a comma-separated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;. You may include both. The default when not supplied is \&quot;published\&quot; only.
     * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the security classification.
     * @param {number} [offset] The number of items to skip before starting to collect the result set.
     * @param {number} [limit] The numbers of items to return. If the value specified is more than the maximum, the result count will be limited to the maximum.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    securityClassificationsListGet(name?: string | undefined, external_id?: string | undefined, status?: string | undefined, valid_parents_for?: string | undefined, offset?: number | undefined, limit?: number | undefined, options?: any): (axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<InlineResponse20051>;
    /**
     * Provision a new security classification.
     * @param {SecurityClassificationSchemaCreate} SecurityClassificationSchemaCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    securityClassificationsPost(SecurityClassificationSchemaCreate: SecurityClassificationSchemaCreate, options?: any): (axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<SuccessfulPostResponseSchema>;
    /**
     * Delete a security classification.
     * @param {string} security_classification_id The Invotra UUID of the security classification.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    securityClassificationsSecurityClassificationIdDelete(security_classification_id: string, options?: any): (axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>;
    /**
     * Get information about the security classification.
     * @param {string} security_classification_id The Invotra UUID of the security classification.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    securityClassificationsSecurityClassificationIdGet(security_classification_id: string, options?: any): (axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<SecurityClassificationSchema>;
    /**
     * Update security classification information.
     * @param {string} security_classification_id The Invotra UUID of the security classification.
     * @param {SecurityClassificationSchemaCommon} SecurityClassificationSchemaCommon
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    securityClassificationsSecurityClassificationIdPut(security_classification_id: string, SecurityClassificationSchemaCommon: SecurityClassificationSchemaCommon, options?: any): (axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<void>;
};
/**
 * SecurityClassificationsApi - factory interface
 * @export
 */
export declare const SecurityClassificationsApiFactory: (configuration?: Configuration | undefined, basePath?: string | undefined, axios?: AxiosInstance | undefined) => {
    /**
     * Search for security classifications. An empty array is returned if no security classifications are found.
     * @param {string} [name] Filter by name. Matches on whole words.
     * @param {string} [external_id] Filter by external ID.
     * @param {string} [status] Filter the list of security classifications on a comma-separated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;. You may include both. The default when not supplied is \&quot;published\&quot; only.
     * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the security classification.
     * @param {number} [offset] The number of items to skip before starting to collect the result set.
     * @param {number} [limit] The numbers of items to return. If the value specified is more than the maximum, the result count will be limited to the maximum.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    securityClassificationsListGet(name?: string | undefined, external_id?: string | undefined, status?: string | undefined, valid_parents_for?: string | undefined, offset?: number | undefined, limit?: number | undefined, options?: any): AxiosPromise<InlineResponse20051>;
    /**
     * Provision a new security classification.
     * @param {SecurityClassificationSchemaCreate} SecurityClassificationSchemaCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    securityClassificationsPost(SecurityClassificationSchemaCreate: SecurityClassificationSchemaCreate, options?: any): AxiosPromise<SuccessfulPostResponseSchema>;
    /**
     * Delete a security classification.
     * @param {string} security_classification_id The Invotra UUID of the security classification.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    securityClassificationsSecurityClassificationIdDelete(security_classification_id: string, options?: any): AxiosPromise<void>;
    /**
     * Get information about the security classification.
     * @param {string} security_classification_id The Invotra UUID of the security classification.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    securityClassificationsSecurityClassificationIdGet(security_classification_id: string, options?: any): AxiosPromise<SecurityClassificationSchema>;
    /**
     * Update security classification information.
     * @param {string} security_classification_id The Invotra UUID of the security classification.
     * @param {SecurityClassificationSchemaCommon} SecurityClassificationSchemaCommon
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    securityClassificationsSecurityClassificationIdPut(security_classification_id: string, SecurityClassificationSchemaCommon: SecurityClassificationSchemaCommon, options?: any): AxiosPromise<void>;
};
/**
 * SecurityClassificationsApi - interface
 * @export
 * @interface SecurityClassificationsApi
 */
export interface SecurityClassificationsApiInterface {
    /**
     * Search for security classifications. An empty array is returned if no security classifications are found.
     * @param {string} [name] Filter by name. Matches on whole words.
     * @param {string} [external_id] Filter by external ID.
     * @param {string} [status] Filter the list of security classifications on a comma-separated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;. You may include both. The default when not supplied is \&quot;published\&quot; only.
     * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the security classification.
     * @param {number} [offset] The number of items to skip before starting to collect the result set.
     * @param {number} [limit] The numbers of items to return. If the value specified is more than the maximum, the result count will be limited to the maximum.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SecurityClassificationsApiInterface
     */
    securityClassificationsListGet(name?: string, external_id?: string, status?: string, valid_parents_for?: string, offset?: number, limit?: number, options?: any): AxiosPromise<InlineResponse20051>;
    /**
     * Provision a new security classification.
     * @param {SecurityClassificationSchemaCreate} SecurityClassificationSchemaCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SecurityClassificationsApiInterface
     */
    securityClassificationsPost(SecurityClassificationSchemaCreate: SecurityClassificationSchemaCreate, options?: any): AxiosPromise<SuccessfulPostResponseSchema>;
    /**
     * Delete a security classification.
     * @param {string} security_classification_id The Invotra UUID of the security classification.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SecurityClassificationsApiInterface
     */
    securityClassificationsSecurityClassificationIdDelete(security_classification_id: string, options?: any): AxiosPromise<void>;
    /**
     * Get information about the security classification.
     * @param {string} security_classification_id The Invotra UUID of the security classification.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SecurityClassificationsApiInterface
     */
    securityClassificationsSecurityClassificationIdGet(security_classification_id: string, options?: any): AxiosPromise<SecurityClassificationSchema>;
    /**
     * Update security classification information.
     * @param {string} security_classification_id The Invotra UUID of the security classification.
     * @param {SecurityClassificationSchemaCommon} SecurityClassificationSchemaCommon
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SecurityClassificationsApiInterface
     */
    securityClassificationsSecurityClassificationIdPut(security_classification_id: string, SecurityClassificationSchemaCommon: SecurityClassificationSchemaCommon, options?: any): AxiosPromise<void>;
}
/**
 * SecurityClassificationsApi - object-oriented interface
 * @export
 * @class SecurityClassificationsApi
 * @extends {BaseAPI}
 */
export declare class SecurityClassificationsApi extends BaseAPI implements SecurityClassificationsApiInterface {
    /**
     * Search for security classifications. An empty array is returned if no security classifications are found.
     * @param {string} [name] Filter by name. Matches on whole words.
     * @param {string} [external_id] Filter by external ID.
     * @param {string} [status] Filter the list of security classifications on a comma-separated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;. You may include both. The default when not supplied is \&quot;published\&quot; only.
     * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the security classification.
     * @param {number} [offset] The number of items to skip before starting to collect the result set.
     * @param {number} [limit] The numbers of items to return. If the value specified is more than the maximum, the result count will be limited to the maximum.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SecurityClassificationsApi
     */
    securityClassificationsListGet(name?: string, external_id?: string, status?: string, valid_parents_for?: string, offset?: number, limit?: number, options?: any): AxiosPromise<InlineResponse20051>;
    /**
     * Provision a new security classification.
     * @param {SecurityClassificationSchemaCreate} SecurityClassificationSchemaCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SecurityClassificationsApi
     */
    securityClassificationsPost(SecurityClassificationSchemaCreate: SecurityClassificationSchemaCreate, options?: any): AxiosPromise<SuccessfulPostResponseSchema>;
    /**
     * Delete a security classification.
     * @param {string} security_classification_id The Invotra UUID of the security classification.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SecurityClassificationsApi
     */
    securityClassificationsSecurityClassificationIdDelete(security_classification_id: string, options?: any): AxiosPromise<void>;
    /**
     * Get information about the security classification.
     * @param {string} security_classification_id The Invotra UUID of the security classification.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SecurityClassificationsApi
     */
    securityClassificationsSecurityClassificationIdGet(security_classification_id: string, options?: any): AxiosPromise<SecurityClassificationSchema>;
    /**
     * Update security classification information.
     * @param {string} security_classification_id The Invotra UUID of the security classification.
     * @param {SecurityClassificationSchemaCommon} SecurityClassificationSchemaCommon
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SecurityClassificationsApi
     */
    securityClassificationsSecurityClassificationIdPut(security_classification_id: string, SecurityClassificationSchemaCommon: SecurityClassificationSchemaCommon, options?: any): AxiosPromise<void>;
}
