// tslint:disable
/**
 * InvotraAPI
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
import * as globalImportUrl from 'url';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, BaseAPI, RequiredError } from '../base';
/**
 * SessionsApi - axios parameter creator
 * @export
 */
export var SessionsApiAxiosParamCreator = function (configuration) {
    return {
        /**
         * Login a user. Use this endpoint if you are authenticating with an individual user rather than an API Key. The session cookie returned in the header should be used for subsequent requests.
         * @param {SessionSchema} SessionSchema
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sessionsLoginPost: function (SessionSchema, options) {
            if (options === void 0) { options = {}; }
            // verify required parameter 'SessionSchema' is not null or undefined
            if (SessionSchema === null || SessionSchema === undefined) {
                throw new RequiredError('SessionSchema', 'Required parameter SessionSchema was null or undefined when calling sessionsLoginPost.');
            }
            var localVarPath = "/sessions/login";
            var localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            var baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            var localVarRequestOptions = __assign(__assign({ method: 'POST' }, baseOptions), options);
            var localVarHeaderParameter = {};
            var localVarQueryParameter = {};
            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarUrlObj.query = __assign(__assign(__assign({}, localVarUrlObj.query), localVarQueryParameter), options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = __assign(__assign({}, localVarHeaderParameter), options.headers);
            var needsSerialization = (typeof SessionSchema !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data = needsSerialization ? JSON.stringify(SessionSchema !== undefined ? SessionSchema : {}) : (SessionSchema || "");
            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Logout the user.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sessionsLogoutPost: function (options) {
            if (options === void 0) { options = {}; }
            var localVarPath = "/sessions/logout";
            var localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            var baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            var localVarRequestOptions = __assign(__assign({ method: 'POST' }, baseOptions), options);
            var localVarHeaderParameter = {};
            var localVarQueryParameter = {};
            // authentication SessionCookieHeader required
            localVarUrlObj.query = __assign(__assign(__assign({}, localVarUrlObj.query), localVarQueryParameter), options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = __assign(__assign({}, localVarHeaderParameter), options.headers);
            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a CSRF token.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sessionsTokenGet: function (options) {
            if (options === void 0) { options = {}; }
            var localVarPath = "/sessions/token";
            var localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            var baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            var localVarRequestOptions = __assign(__assign({ method: 'GET' }, baseOptions), options);
            var localVarHeaderParameter = {};
            var localVarQueryParameter = {};
            // authentication SessionCookieHeader required
            localVarUrlObj.query = __assign(__assign(__assign({}, localVarUrlObj.query), localVarQueryParameter), options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = __assign(__assign({}, localVarHeaderParameter), options.headers);
            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Exchange a temporary single-use token for a valid user session and CSRF token. This is intended for use by mobile apps.
         * @param {AuthTokenSchema} AuthTokenSchema
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sessionsTokenPost: function (AuthTokenSchema, options) {
            if (options === void 0) { options = {}; }
            // verify required parameter 'AuthTokenSchema' is not null or undefined
            if (AuthTokenSchema === null || AuthTokenSchema === undefined) {
                throw new RequiredError('AuthTokenSchema', 'Required parameter AuthTokenSchema was null or undefined when calling sessionsTokenPost.');
            }
            var localVarPath = "/sessions/token";
            var localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            var baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            var localVarRequestOptions = __assign(__assign({ method: 'POST' }, baseOptions), options);
            var localVarHeaderParameter = {};
            var localVarQueryParameter = {};
            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarUrlObj.query = __assign(__assign(__assign({}, localVarUrlObj.query), localVarQueryParameter), options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = __assign(__assign({}, localVarHeaderParameter), options.headers);
            var needsSerialization = (typeof AuthTokenSchema !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data = needsSerialization ? JSON.stringify(AuthTokenSchema !== undefined ? AuthTokenSchema : {}) : (AuthTokenSchema || "");
            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    };
};
/**
 * SessionsApi - functional programming interface
 * @export
 */
export var SessionsApiFp = function (configuration) {
    return {
        /**
         * Login a user. Use this endpoint if you are authenticating with an individual user rather than an API Key. The session cookie returned in the header should be used for subsequent requests.
         * @param {SessionSchema} SessionSchema
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sessionsLoginPost: function (SessionSchema, options) {
            var localVarAxiosArgs = SessionsApiAxiosParamCreator(configuration).sessionsLoginPost(SessionSchema, options);
            return function (axios, basePath) {
                if (axios === void 0) { axios = globalAxios; }
                if (basePath === void 0) { basePath = BASE_PATH; }
                var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Logout the user.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sessionsLogoutPost: function (options) {
            var localVarAxiosArgs = SessionsApiAxiosParamCreator(configuration).sessionsLogoutPost(options);
            return function (axios, basePath) {
                if (axios === void 0) { axios = globalAxios; }
                if (basePath === void 0) { basePath = BASE_PATH; }
                var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Returns a CSRF token.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sessionsTokenGet: function (options) {
            var localVarAxiosArgs = SessionsApiAxiosParamCreator(configuration).sessionsTokenGet(options);
            return function (axios, basePath) {
                if (axios === void 0) { axios = globalAxios; }
                if (basePath === void 0) { basePath = BASE_PATH; }
                var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Exchange a temporary single-use token for a valid user session and CSRF token. This is intended for use by mobile apps.
         * @param {AuthTokenSchema} AuthTokenSchema
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sessionsTokenPost: function (AuthTokenSchema, options) {
            var localVarAxiosArgs = SessionsApiAxiosParamCreator(configuration).sessionsTokenPost(AuthTokenSchema, options);
            return function (axios, basePath) {
                if (axios === void 0) { axios = globalAxios; }
                if (basePath === void 0) { basePath = BASE_PATH; }
                var axiosRequestArgs = __assign(__assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
    };
};
/**
 * SessionsApi - factory interface
 * @export
 */
export var SessionsApiFactory = function (configuration, basePath, axios) {
    return {
        /**
         * Login a user. Use this endpoint if you are authenticating with an individual user rather than an API Key. The session cookie returned in the header should be used for subsequent requests.
         * @param {SessionSchema} SessionSchema
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sessionsLoginPost: function (SessionSchema, options) {
            return SessionsApiFp(configuration).sessionsLoginPost(SessionSchema, options)(axios, basePath);
        },
        /**
         * Logout the user.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sessionsLogoutPost: function (options) {
            return SessionsApiFp(configuration).sessionsLogoutPost(options)(axios, basePath);
        },
        /**
         * Returns a CSRF token.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sessionsTokenGet: function (options) {
            return SessionsApiFp(configuration).sessionsTokenGet(options)(axios, basePath);
        },
        /**
         * Exchange a temporary single-use token for a valid user session and CSRF token. This is intended for use by mobile apps.
         * @param {AuthTokenSchema} AuthTokenSchema
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sessionsTokenPost: function (AuthTokenSchema, options) {
            return SessionsApiFp(configuration).sessionsTokenPost(AuthTokenSchema, options)(axios, basePath);
        },
    };
};
/**
 * SessionsApi - object-oriented interface
 * @export
 * @class SessionsApi
 * @extends {BaseAPI}
 */
var SessionsApi = /** @class */ (function (_super) {
    __extends(SessionsApi, _super);
    function SessionsApi() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    /**
     * Login a user. Use this endpoint if you are authenticating with an individual user rather than an API Key. The session cookie returned in the header should be used for subsequent requests.
     * @param {SessionSchema} SessionSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionsApi
     */
    SessionsApi.prototype.sessionsLoginPost = function (SessionSchema, options) {
        return SessionsApiFp(this.configuration).sessionsLoginPost(SessionSchema, options)(this.axios, this.basePath);
    };
    /**
     * Logout the user.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionsApi
     */
    SessionsApi.prototype.sessionsLogoutPost = function (options) {
        return SessionsApiFp(this.configuration).sessionsLogoutPost(options)(this.axios, this.basePath);
    };
    /**
     * Returns a CSRF token.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionsApi
     */
    SessionsApi.prototype.sessionsTokenGet = function (options) {
        return SessionsApiFp(this.configuration).sessionsTokenGet(options)(this.axios, this.basePath);
    };
    /**
     * Exchange a temporary single-use token for a valid user session and CSRF token. This is intended for use by mobile apps.
     * @param {AuthTokenSchema} AuthTokenSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionsApi
     */
    SessionsApi.prototype.sessionsTokenPost = function (AuthTokenSchema, options) {
        return SessionsApiFp(this.configuration).sessionsTokenPost(AuthTokenSchema, options)(this.axios, this.basePath);
    };
    return SessionsApi;
}(BaseAPI));
export { SessionsApi };
//# sourceMappingURL=sessions-api.js.map