/**
 * InvotraAPI
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * The category of the comment.
 * @export
 * @interface CommentSchemaCategory
 */
export interface CommentSchemaCategory {
    /**
     * The name of the comment category.
     * @type {string}
     * @memberof CommentSchemaCategory
     */
    name: string;
    /**
     * This is the Invotra UUID of the comment category.
     * @type {string}
     * @memberof CommentSchemaCategory
     */
    uuid: string;
}
