/**
 * Invotra API
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface EventStatusSchemaCommon
 */
export interface EventStatusSchemaCommon {
    /**
     * Name of the event status.
     * @type {string}
     * @memberof EventStatusSchemaCommon
     */
    name?: string;
    /**
     * Description of the event status.
     * @type {string}
     * @memberof EventStatusSchemaCommon
     */
    description?: string;
    /**
     * The event status external reference id.
     * @type {string}
     * @memberof EventStatusSchemaCommon
     */
    external_id?: string;
    /**
     * Invotra UUID of the parent event status.
     * @type {string}
     * @memberof EventStatusSchemaCommon
     */
    parent_uuid?: string;
    /**
     * Indicates that this event status is published.
     * @type {boolean}
     * @memberof EventStatusSchemaCommon
     */
    published?: boolean;
    /**
     * Determines the position of an event status in the hierarchy in relation to its siblings.
     * @type {number}
     * @memberof EventStatusSchemaCommon
     */
    weight?: number;
}
