/**
 * Invotra API
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface GroupMetricsSchema
 */
export interface GroupMetricsSchema {
    /**
     * Total likes of content and replies across all groups.
     * @type {number}
     * @memberof GroupMetricsSchema
     */
    likes?: number;
    /**
     * Total number of users that are a member of at least one group.
     * @type {number}
     * @memberof GroupMetricsSchema
     */
    members_count?: number;
}
