/**
 * Invotra API
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileSchema } from './file-schema';
/**
 *
 * @export
 * @interface ManualListingSchema
 */
export interface ManualListingSchema {
    /**
     * Invotra UUID of Manual (root page)
     * @type {string}
     * @memberof ManualListingSchema
     */
    uuid?: string;
    /**
     * Manual title
     * @type {string}
     * @memberof ManualListingSchema
     */
    title?: string;
    /**
     * Manual Cover Image
     * @type {FileSchema}
     * @memberof ManualListingSchema
     */
    image?: FileSchema;
}
