/**
 * Invotra API
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomContentSchemaUpdateAllOfAttachments } from './custom-content-schema-update-all-of-attachments';
import { CustomContentSchemaUpdateAllOfGrades } from './custom-content-schema-update-all-of-grades';
import { CustomContentSchemaUpdateAllOfLocations } from './custom-content-schema-update-all-of-locations';
import { CustomContentSchemaUpdateAllOfRegions } from './custom-content-schema-update-all-of-regions';
import { PageSchemaCreateAllOfAuthor } from './page-schema-create-all-of-author';
import { PageSchemaCreateAllOfOwner } from './page-schema-create-all-of-owner';
import { PageSchemaCreateAllOfTeam } from './page-schema-create-all-of-team';
import { PageSchemaUpdateAllOfImage } from './page-schema-update-all-of-image';
import { PageSchemaUpdateAllOfSiteSection } from './page-schema-update-all-of-site-section';
/**
 *
 * @export
 * @interface PageSchemaCreateAllOf
 */
export interface PageSchemaCreateAllOf {
    /**
     *
     * @type {PageSchemaUpdateAllOfSiteSection}
     * @memberof PageSchemaCreateAllOf
     */
    site_section: PageSchemaUpdateAllOfSiteSection;
    /**
     *
     * @type {PageSchemaUpdateAllOfImage}
     * @memberof PageSchemaCreateAllOf
     */
    image?: PageSchemaUpdateAllOfImage;
    /**
     *
     * @type {PageSchemaCreateAllOfAuthor}
     * @memberof PageSchemaCreateAllOf
     */
    author?: PageSchemaCreateAllOfAuthor;
    /**
     * The attached files of this page.
     * @type {Array<CustomContentSchemaUpdateAllOfAttachments>}
     * @memberof PageSchemaCreateAllOf
     */
    attachments?: Array<CustomContentSchemaUpdateAllOfAttachments>;
    /**
     *
     * @type {PageSchemaCreateAllOfOwner}
     * @memberof PageSchemaCreateAllOf
     */
    owner?: PageSchemaCreateAllOfOwner;
    /**
     *
     * @type {PageSchemaCreateAllOfTeam}
     * @memberof PageSchemaCreateAllOf
     */
    team?: PageSchemaCreateAllOfTeam;
    /**
     * The locations targeting this page.
     * @type {Array<CustomContentSchemaUpdateAllOfLocations>}
     * @memberof PageSchemaCreateAllOf
     */
    locations?: Array<CustomContentSchemaUpdateAllOfLocations>;
    /**
     * The grades targeting this page.
     * @type {Array<CustomContentSchemaUpdateAllOfGrades>}
     * @memberof PageSchemaCreateAllOf
     */
    grades?: Array<CustomContentSchemaUpdateAllOfGrades>;
    /**
     * The regions targeting this page.
     * @type {Array<CustomContentSchemaUpdateAllOfRegions>}
     * @memberof PageSchemaCreateAllOf
     */
    regions?: Array<CustomContentSchemaUpdateAllOfRegions>;
}
