/**
 * InvotraAPI
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PersonTypeSchemaAllOf
 */
export interface PersonTypeSchemaAllOf {
    /**
     * Invotra UUID of the person type.
     * @type {string}
     * @memberof PersonTypeSchemaAllOf
     */
    uuid?: string;
    /**
     * Indicates that this person type has children.
     * @type {boolean}
     * @memberof PersonTypeSchemaAllOf
     */
    has_children?: boolean;
}
