/**
 * InvotraAPI
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PolicyTypeSchemaCommon
 */
export interface PolicyTypeSchemaCommon {
    /**
     * Name of the policy type.
     * @type {string}
     * @memberof PolicyTypeSchemaCommon
     */
    name?: string;
    /**
     * Description of the policy type.
     * @type {string}
     * @memberof PolicyTypeSchemaCommon
     */
    description?: string;
    /**
     * The policy type external reference id.
     * @type {string}
     * @memberof PolicyTypeSchemaCommon
     */
    external_id?: string;
    /**
     * Invotra UUID of the parent policy type.
     * @type {string}
     * @memberof PolicyTypeSchemaCommon
     */
    parent_uuid?: string;
    /**
     * Indicates that this policy type is published.
     * @type {boolean}
     * @memberof PolicyTypeSchemaCommon
     */
    published?: boolean;
    /**
     * Determines the position of a policy type in the hierarchy in relation to its siblings.
     * @type {number}
     * @memberof PolicyTypeSchemaCommon
     */
    weight?: number;
}
