/**
 * InvotraAPI
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomContentSchemaUpdateAllOfGrades } from './custom-content-schema-update-all-of-grades';
import { CustomContentSchemaUpdateAllOfLocations } from './custom-content-schema-update-all-of-locations';
import { CustomContentSchemaUpdateAllOfRegions } from './custom-content-schema-update-all-of-regions';
import { PromotionSchemaUpdateAllOfAuthor } from './promotion-schema-update-all-of-author';
import { PromotionSchemaUpdateAllOfImage } from './promotion-schema-update-all-of-image';
import { PromotionSchemaUpdateAllOfOwner } from './promotion-schema-update-all-of-owner';
import { PromotionSchemaUpdateAllOfSiteSection } from './promotion-schema-update-all-of-site-section';
import { PromotionSchemaUpdateAllOfTeam } from './promotion-schema-update-all-of-team';
/**
 *
 * @export
 * @interface PromotionSchemaUpdateAllOf
 */
export interface PromotionSchemaUpdateAllOf {
    /**
     *
     * @type {PromotionSchemaUpdateAllOfSiteSection}
     * @memberof PromotionSchemaUpdateAllOf
     */
    site_section?: PromotionSchemaUpdateAllOfSiteSection;
    /**
     *
     * @type {PromotionSchemaUpdateAllOfImage}
     * @memberof PromotionSchemaUpdateAllOf
     */
    image?: PromotionSchemaUpdateAllOfImage;
    /**
     *
     * @type {PromotionSchemaUpdateAllOfOwner}
     * @memberof PromotionSchemaUpdateAllOf
     */
    owner?: PromotionSchemaUpdateAllOfOwner;
    /**
     *
     * @type {PromotionSchemaUpdateAllOfAuthor}
     * @memberof PromotionSchemaUpdateAllOf
     */
    author?: PromotionSchemaUpdateAllOfAuthor;
    /**
     *
     * @type {PromotionSchemaUpdateAllOfTeam}
     * @memberof PromotionSchemaUpdateAllOf
     */
    team?: PromotionSchemaUpdateAllOfTeam;
    /**
     * The locations targeting this promotion.
     * @type {Array<CustomContentSchemaUpdateAllOfLocations>}
     * @memberof PromotionSchemaUpdateAllOf
     */
    locations?: Array<CustomContentSchemaUpdateAllOfLocations>;
    /**
     * The grades targeting this promotion.
     * @type {Array<CustomContentSchemaUpdateAllOfGrades>}
     * @memberof PromotionSchemaUpdateAllOf
     */
    grades?: Array<CustomContentSchemaUpdateAllOfGrades>;
    /**
     * The regions targeting this promotion.
     * @type {Array<CustomContentSchemaUpdateAllOfRegions>}
     * @memberof PromotionSchemaUpdateAllOf
     */
    regions?: Array<CustomContentSchemaUpdateAllOfRegions>;
    /**
     * The timestamp of the schedule date (in seconds). If present the content is scheduled for a workflow state change, if not, the workflow state will be changed immediately.
     * @type {number}
     * @memberof PromotionSchemaUpdateAllOf
     */
    schedule_date_timestamp?: number;
}
