// tslint:disable
/**
 * InvotraAPI
 * In general most fields are optional for update (PUT) requests; you can leave them blank (pass an empty string / array / whatever as appropriate) to clear them, or omit the key to leave them unchanged.
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';

import { GroupCategorySchema } from '../model';
import { GroupCategorySchemaCommon } from '../model';
import { GroupCategorySchemaCreate } from '../model';
import { InlineResponse20039 } from '../model';
import { SuccessfulPostResponseSchema } from '../model';
/**
 * GroupCategoriesApi - axios parameter creator
 * @export
 */
export const GroupCategoriesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Delete a group category.
         * @param {string} group_category_id The Invotra UUID of the group category.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupCategoriesGroupCategoryIdDelete(group_category_id: string, options: any = {}): RequestArgs {
            // verify required parameter 'group_category_id' is not null or undefined
            if (group_category_id === null || group_category_id === undefined) {
                throw new RequiredError('group_category_id','Required parameter group_category_id was null or undefined when calling groupCategoriesGroupCategoryIdDelete.');
            }
            const localVarPath = `/group_categories/{group_category_id}`
                .replace(`{${"group_category_id"}}`, encodeURIComponent(String(group_category_id)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication APIKeyHeader required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("X-API-Key")
                    : configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }

            // authentication CognitoJwt required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("CognitoJwt", ["invotra/group_categories:write"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            // authentication SessionCookieHeader required


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get information about the group category.
         * @param {string} group_category_id The Invotra UUID of the group category.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupCategoriesGroupCategoryIdGet(group_category_id: string, options: any = {}): RequestArgs {
            // verify required parameter 'group_category_id' is not null or undefined
            if (group_category_id === null || group_category_id === undefined) {
                throw new RequiredError('group_category_id','Required parameter group_category_id was null or undefined when calling groupCategoriesGroupCategoryIdGet.');
            }
            const localVarPath = `/group_categories/{group_category_id}`
                .replace(`{${"group_category_id"}}`, encodeURIComponent(String(group_category_id)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication APIKeyHeader required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("X-API-Key")
                    : configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }

            // authentication CognitoJwt required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("CognitoJwt", ["invotra/group_categories:read"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            // authentication SessionCookieHeader required


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update group category information.
         * @param {string} group_category_id The Invotra UUID of the group category.
         * @param {GroupCategorySchemaCommon} GroupCategorySchemaCommon 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupCategoriesGroupCategoryIdPut(group_category_id: string, GroupCategorySchemaCommon: GroupCategorySchemaCommon, options: any = {}): RequestArgs {
            // verify required parameter 'group_category_id' is not null or undefined
            if (group_category_id === null || group_category_id === undefined) {
                throw new RequiredError('group_category_id','Required parameter group_category_id was null or undefined when calling groupCategoriesGroupCategoryIdPut.');
            }
            // verify required parameter 'GroupCategorySchemaCommon' is not null or undefined
            if (GroupCategorySchemaCommon === null || GroupCategorySchemaCommon === undefined) {
                throw new RequiredError('GroupCategorySchemaCommon','Required parameter GroupCategorySchemaCommon was null or undefined when calling groupCategoriesGroupCategoryIdPut.');
            }
            const localVarPath = `/group_categories/{group_category_id}`
                .replace(`{${"group_category_id"}}`, encodeURIComponent(String(group_category_id)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication APIKeyHeader required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("X-API-Key")
                    : configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }

            // authentication CognitoJwt required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("CognitoJwt", ["invotra/group_categories:write"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            // authentication SessionCookieHeader required


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};
            const needsSerialization = (typeof GroupCategorySchemaCommon !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(GroupCategorySchemaCommon !== undefined ? GroupCategorySchemaCommon : {}) : (GroupCategorySchemaCommon || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Search for group categories. An empty array is returned if no group categories are found.
         * @param {string} [name] Filter by name. Matches on whole words.
         * @param {string} [external_id] Filter by external ID.
         * @param {string} [status] Filter the list of group categories on a comma seperated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;, you may inlude both. The default when not supplied is \&quot;published\&quot; only.
         * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the group category.
         * @param {number} [offset] The number of items to skip before starting to collect the result set.
         * @param {number} [limit] The numbers of items to return.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupCategoriesListGet(name?: string, external_id?: string, status?: string, valid_parents_for?: string, offset?: number, limit?: number, options: any = {}): RequestArgs {
            const localVarPath = `/group_categories/list`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication APIKeyHeader required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("X-API-Key")
                    : configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }

            // authentication CognitoJwt required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("CognitoJwt", ["invotra/group_categories:read"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            // authentication SessionCookieHeader required

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (external_id !== undefined) {
                localVarQueryParameter['external_id'] = external_id;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (valid_parents_for !== undefined) {
                localVarQueryParameter['valid_parents_for'] = valid_parents_for;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Provision a new group category.
         * @param {GroupCategorySchemaCreate} GroupCategorySchemaCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupCategoriesPost(GroupCategorySchemaCreate: GroupCategorySchemaCreate, options: any = {}): RequestArgs {
            // verify required parameter 'GroupCategorySchemaCreate' is not null or undefined
            if (GroupCategorySchemaCreate === null || GroupCategorySchemaCreate === undefined) {
                throw new RequiredError('GroupCategorySchemaCreate','Required parameter GroupCategorySchemaCreate was null or undefined when calling groupCategoriesPost.');
            }
            const localVarPath = `/group_categories`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication APIKeyHeader required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? configuration.apiKey("X-API-Key")
                    : configuration.apiKey;
                localVarHeaderParameter["X-API-Key"] = localVarApiKeyValue;
            }

            // authentication CognitoJwt required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("CognitoJwt", ["invotra/group_categories:write"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            // authentication SessionCookieHeader required


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};
            const needsSerialization = (typeof GroupCategorySchemaCreate !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(GroupCategorySchemaCreate !== undefined ? GroupCategorySchemaCreate : {}) : (GroupCategorySchemaCreate || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GroupCategoriesApi - functional programming interface
 * @export
 */
export const GroupCategoriesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Delete a group category.
         * @param {string} group_category_id The Invotra UUID of the group category.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupCategoriesGroupCategoryIdDelete(group_category_id: string, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void> {
            const localVarAxiosArgs = GroupCategoriesApiAxiosParamCreator(configuration).groupCategoriesGroupCategoryIdDelete(group_category_id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get information about the group category.
         * @param {string} group_category_id The Invotra UUID of the group category.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupCategoriesGroupCategoryIdGet(group_category_id: string, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupCategorySchema> {
            const localVarAxiosArgs = GroupCategoriesApiAxiosParamCreator(configuration).groupCategoriesGroupCategoryIdGet(group_category_id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Update group category information.
         * @param {string} group_category_id The Invotra UUID of the group category.
         * @param {GroupCategorySchemaCommon} GroupCategorySchemaCommon 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupCategoriesGroupCategoryIdPut(group_category_id: string, GroupCategorySchemaCommon: GroupCategorySchemaCommon, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void> {
            const localVarAxiosArgs = GroupCategoriesApiAxiosParamCreator(configuration).groupCategoriesGroupCategoryIdPut(group_category_id, GroupCategorySchemaCommon, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Search for group categories. An empty array is returned if no group categories are found.
         * @param {string} [name] Filter by name. Matches on whole words.
         * @param {string} [external_id] Filter by external ID.
         * @param {string} [status] Filter the list of group categories on a comma seperated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;, you may inlude both. The default when not supplied is \&quot;published\&quot; only.
         * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the group category.
         * @param {number} [offset] The number of items to skip before starting to collect the result set.
         * @param {number} [limit] The numbers of items to return.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupCategoriesListGet(name?: string, external_id?: string, status?: string, valid_parents_for?: string, offset?: number, limit?: number, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse20039> {
            const localVarAxiosArgs = GroupCategoriesApiAxiosParamCreator(configuration).groupCategoriesListGet(name, external_id, status, valid_parents_for, offset, limit, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Provision a new group category.
         * @param {GroupCategorySchemaCreate} GroupCategorySchemaCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupCategoriesPost(GroupCategorySchemaCreate: GroupCategorySchemaCreate, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessfulPostResponseSchema> {
            const localVarAxiosArgs = GroupCategoriesApiAxiosParamCreator(configuration).groupCategoriesPost(GroupCategorySchemaCreate, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * GroupCategoriesApi - factory interface
 * @export
 */
export const GroupCategoriesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Delete a group category.
         * @param {string} group_category_id The Invotra UUID of the group category.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupCategoriesGroupCategoryIdDelete(group_category_id: string, options?: any): AxiosPromise<void> {
            return GroupCategoriesApiFp(configuration).groupCategoriesGroupCategoryIdDelete(group_category_id, options)(axios, basePath);
        },
        /**
         * Get information about the group category.
         * @param {string} group_category_id The Invotra UUID of the group category.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupCategoriesGroupCategoryIdGet(group_category_id: string, options?: any): AxiosPromise<GroupCategorySchema> {
            return GroupCategoriesApiFp(configuration).groupCategoriesGroupCategoryIdGet(group_category_id, options)(axios, basePath);
        },
        /**
         * Update group category information.
         * @param {string} group_category_id The Invotra UUID of the group category.
         * @param {GroupCategorySchemaCommon} GroupCategorySchemaCommon 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupCategoriesGroupCategoryIdPut(group_category_id: string, GroupCategorySchemaCommon: GroupCategorySchemaCommon, options?: any): AxiosPromise<void> {
            return GroupCategoriesApiFp(configuration).groupCategoriesGroupCategoryIdPut(group_category_id, GroupCategorySchemaCommon, options)(axios, basePath);
        },
        /**
         * Search for group categories. An empty array is returned if no group categories are found.
         * @param {string} [name] Filter by name. Matches on whole words.
         * @param {string} [external_id] Filter by external ID.
         * @param {string} [status] Filter the list of group categories on a comma seperated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;, you may inlude both. The default when not supplied is \&quot;published\&quot; only.
         * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the group category.
         * @param {number} [offset] The number of items to skip before starting to collect the result set.
         * @param {number} [limit] The numbers of items to return.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupCategoriesListGet(name?: string, external_id?: string, status?: string, valid_parents_for?: string, offset?: number, limit?: number, options?: any): AxiosPromise<InlineResponse20039> {
            return GroupCategoriesApiFp(configuration).groupCategoriesListGet(name, external_id, status, valid_parents_for, offset, limit, options)(axios, basePath);
        },
        /**
         * Provision a new group category.
         * @param {GroupCategorySchemaCreate} GroupCategorySchemaCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        groupCategoriesPost(GroupCategorySchemaCreate: GroupCategorySchemaCreate, options?: any): AxiosPromise<SuccessfulPostResponseSchema> {
            return GroupCategoriesApiFp(configuration).groupCategoriesPost(GroupCategorySchemaCreate, options)(axios, basePath);
        },
    };
};

/**
 * GroupCategoriesApi - interface
 * @export
 * @interface GroupCategoriesApi
 */
export interface GroupCategoriesApiInterface {
    /**
     * Delete a group category.
     * @param {string} group_category_id The Invotra UUID of the group category.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupCategoriesApiInterface
     */
    groupCategoriesGroupCategoryIdDelete(group_category_id: string, options?: any): AxiosPromise<void>;

    /**
     * Get information about the group category.
     * @param {string} group_category_id The Invotra UUID of the group category.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupCategoriesApiInterface
     */
    groupCategoriesGroupCategoryIdGet(group_category_id: string, options?: any): AxiosPromise<GroupCategorySchema>;

    /**
     * Update group category information.
     * @param {string} group_category_id The Invotra UUID of the group category.
     * @param {GroupCategorySchemaCommon} GroupCategorySchemaCommon 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupCategoriesApiInterface
     */
    groupCategoriesGroupCategoryIdPut(group_category_id: string, GroupCategorySchemaCommon: GroupCategorySchemaCommon, options?: any): AxiosPromise<void>;

    /**
     * Search for group categories. An empty array is returned if no group categories are found.
     * @param {string} [name] Filter by name. Matches on whole words.
     * @param {string} [external_id] Filter by external ID.
     * @param {string} [status] Filter the list of group categories on a comma seperated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;, you may inlude both. The default when not supplied is \&quot;published\&quot; only.
     * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the group category.
     * @param {number} [offset] The number of items to skip before starting to collect the result set.
     * @param {number} [limit] The numbers of items to return.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupCategoriesApiInterface
     */
    groupCategoriesListGet(name?: string, external_id?: string, status?: string, valid_parents_for?: string, offset?: number, limit?: number, options?: any): AxiosPromise<InlineResponse20039>;

    /**
     * Provision a new group category.
     * @param {GroupCategorySchemaCreate} GroupCategorySchemaCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupCategoriesApiInterface
     */
    groupCategoriesPost(GroupCategorySchemaCreate: GroupCategorySchemaCreate, options?: any): AxiosPromise<SuccessfulPostResponseSchema>;

}

/**
 * GroupCategoriesApi - object-oriented interface
 * @export
 * @class GroupCategoriesApi
 * @extends {BaseAPI}
 */
export class GroupCategoriesApi extends BaseAPI implements GroupCategoriesApiInterface {
    /**
     * Delete a group category.
     * @param {string} group_category_id The Invotra UUID of the group category.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupCategoriesApi
     */
    public groupCategoriesGroupCategoryIdDelete(group_category_id: string, options?: any) {
        return GroupCategoriesApiFp(this.configuration).groupCategoriesGroupCategoryIdDelete(group_category_id, options)(this.axios, this.basePath);
    }

    /**
     * Get information about the group category.
     * @param {string} group_category_id The Invotra UUID of the group category.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupCategoriesApi
     */
    public groupCategoriesGroupCategoryIdGet(group_category_id: string, options?: any) {
        return GroupCategoriesApiFp(this.configuration).groupCategoriesGroupCategoryIdGet(group_category_id, options)(this.axios, this.basePath);
    }

    /**
     * Update group category information.
     * @param {string} group_category_id The Invotra UUID of the group category.
     * @param {GroupCategorySchemaCommon} GroupCategorySchemaCommon 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupCategoriesApi
     */
    public groupCategoriesGroupCategoryIdPut(group_category_id: string, GroupCategorySchemaCommon: GroupCategorySchemaCommon, options?: any) {
        return GroupCategoriesApiFp(this.configuration).groupCategoriesGroupCategoryIdPut(group_category_id, GroupCategorySchemaCommon, options)(this.axios, this.basePath);
    }

    /**
     * Search for group categories. An empty array is returned if no group categories are found.
     * @param {string} [name] Filter by name. Matches on whole words.
     * @param {string} [external_id] Filter by external ID.
     * @param {string} [status] Filter the list of group categories on a comma seperated list of statuses. Valid statuses are \&quot;published\&quot; and \&quot;unpublished\&quot;, you may inlude both. The default when not supplied is \&quot;published\&quot; only.
     * @param {string} [valid_parents_for] Filter out invalid parents (self and children) for the specified Invotra UUID of the group category.
     * @param {number} [offset] The number of items to skip before starting to collect the result set.
     * @param {number} [limit] The numbers of items to return.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupCategoriesApi
     */
    public groupCategoriesListGet(name?: string, external_id?: string, status?: string, valid_parents_for?: string, offset?: number, limit?: number, options?: any) {
        return GroupCategoriesApiFp(this.configuration).groupCategoriesListGet(name, external_id, status, valid_parents_for, offset, limit, options)(this.axios, this.basePath);
    }

    /**
     * Provision a new group category.
     * @param {GroupCategorySchemaCreate} GroupCategorySchemaCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupCategoriesApi
     */
    public groupCategoriesPost(GroupCategorySchemaCreate: GroupCategorySchemaCreate, options?: any) {
        return GroupCategoriesApiFp(this.configuration).groupCategoriesPost(GroupCategorySchemaCreate, options)(this.axios, this.basePath);
    }

}
